### ISSUE TITLE
use abc for Edit class to ensure method definition

### ISSUE THREAD

**Issue by reece** [biocommons/hgvs#178]
Originally reported by: **Reece Hart (Bitbucket: [reece](http://bitbucket.org/reece), GitHub: [reece](http://github.com/reece))**

----------------------------------------

Related to: #178, #301, #347

Issue #175, in which the type method was implemented only for some subclasses of the Edit class, suggests that we use the abc package and better subclassing to improve consistency.

It's unclear whether/how this interacts with recordtype used by current classes.

----------------------------------------
- Bitbucket: https://bitbucket.org/biocommons/hgvs/issue/178

**Comment by davmlaw** [comment]
Fixed with pull request
