### ISSUE TITLE
implement tool to identify plausible variants from incomplete/improper variants

### ISSUE THREAD

**Issue by reece** [biocommons/hgvs#216]
Originally reported by: **Reece Hart (Bitbucket: [reece](http://bitbucket.org/reece), GitHub: [reece](http://github.com/reece))**

----------------------------------------

Given an incomplete or improperly formatted variant, enumerate plausible interpretations.

For example, for GENE:c.123A>T, identify transcripts for which this c. variant is possible, if any. This requires constructing each variant and returning only those that validate.

Do this for transcripts first, then extend to proteins.

Notify Fah Sathirapongsasuti (23) and Lawrence Lee, Geoff Nilsen, Emily Hare (Invitae) when implemented.

----------------------------------------
- Bitbucket: https://bitbucket.org/biocommons/hgvs/issue/216

**Comment by davmlaw** [comment]
This is a dupe of #517 closing this one as there is more info and conversation there
