### ISSUE TITLE
Indels that overlap sequence discrepancies are incorrectly/oddly mapped

### ISSUE THREAD

**Issue by reece** [biocommons/hgvs#259]
Originally reported by: **Reece Hart (Bitbucket: [reece](http://bitbucket.org/reece), GitHub: [reece](http://github.com/reece))**

----------------------------------------

Related: #353, #208

NM_000116.4:n.207_208insT and NM_000348.3:n.159del correspond exactly to discrepancies between those transcripts and the genome. 

Projecting them onto g. coordinates results in the following:

```
NM_000116.4:n.207_208insT   NM_000116.4:c.-120_-119insT NC_000023.10:g.153640060_153640062insT  ...
NM_000348.3:n.159del        NM_000348.3:c.88delC        NC_000002.11:g.31805883_31805882delGC  ...
```

Projecting those variants into c. coordinates works fine, of course. Also, projecting MNVs works, even when there are length-preserving discrepancies between the transcript and genome.

This issue needs to figure out the right behavior (and warnings?) for variants like these, and variants that subsume tx-ref discrepancies also.

----------------------------------------
- Bitbucket: https://bitbucket.org/biocommons/hgvs/issue/259

**Comment by icebert** [comment]
Resolved in hgvs release 1.2.0
