### ISSUE TITLE
Support removing reference sequence in formatter

### ISSUE THREAD

**Issue by icebert** [biocommons/hgvs#404]
When printing very large variant like NC_000001.10:g.102673499_102843725del, it will take several pages to print the reference sequence of this variant if the reference sequence is included. So I think the formatter should be able to be configured to remove the reference sequence, like:

`var.format(conf = {'remove_ref_seq' : True})`

**Comment by reece** [comment]
I like this in principle!

Instead of a boolean, how about max length of deleted sequence?

E.g.,
* `{'max_del_length': 50}` would truncate if len is 51 or greater
* `{'max_del_length': 0}` would always remove the sequence

**Comment by icebert** [comment]
Good idea! I'll implement this.

**Comment by icebert** [comment]
Hi Reece, I just updated the pull request. I named the option to be 'max_ref_length' because reference sequence of not only del but also dup would subject to the constraint. By default, the max_ref_length is None, which means no constraint on the ref sequence length.

**Comment by reece** [comment]
Good catch. I'd forgotten about dups.

What are the tradeoffs of None v. 0? Both are equally correct, but I think I prefer 0 for it's non-duplication of information and reduction of surprises (i.e., variants with really long del/dup sequences in them).

What do you think?

**Comment by icebert** [comment]
Previous code would include the references no matter how  long it is, so to make the results compatible to previous results, the default value of max_ref_length is None. But personally I also prefer the max_ref_length to be 0.

**Comment by reece** [comment]
Me too. Let's make it 0. It's a major release, so we can change behavior like this.
