### ISSUE TITLE
error message when importing varianrmapper

### ISSUE THREAD

**Issue by leoSeattle** [biocommons/hgvs#408]
after installation, the first attempt of  "import hgvs.variantmapper" gave a warning about "bioutils", I upgraded the bioutils. the second attempt of "import hgvs.variantmapper" gave following error:
>>> import hgvs.variantmapper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/hgvs/variantmapper.py", line 8, i                                       n <module>
    from bioutils.accessions import primary_assembly_accessions
ImportError: cannot import name primary_assembly_accessions

**Comment by reece** [comment]
Thanks for the report.

hgvs 0.4.x requires bioutils < 0.2.
hgvs 1.0.0a1 requires bioutils >= 0.2.

It sounds like you've manually installed bioutils, which would install 0.2.2 (the latest).

Please try `pip install "bioutils<0.2"` (quotes are important) and report back.

**Comment by leoSeattle** [comment]
Thanks for response, that works
