### ISSUE TITLE
Bug in normalizing ident var that is written as delins

### ISSUE THREAD

**Issue by icebert** [biocommons/hgvs#409]
When I was normalizing the clinvar variants, I found the variant

> NC_000003.12:g.46709584_46709610del27insAAGAAGAAGAAGAAGAAGAAGAAGAAG

which reference sequence is in fact the same as the alt sequence. So this is an ident variant. But current normalizer treats this variant to be delins and shuffles the var till the chromosome end.

**Comment by reece** [comment]
Closed in PR #410
