### ISSUE TITLE
Ensure that c. coordinate is within CDS bounds

### ISSUE THREAD

**Issue by reece** [biocommons/hgvs#426]
We don't verify that a c. variant is within CDS bounds. This causes bugs in (at least) c_to_p. An example is #425.

At a minimum, we should add bounds checking to the ExtrinsicValidator class.

However, EV isn't invoked during projection because it's a bit expensive. One option is to start running EV by default, but also provide a way for callers to disable validation (i.e., enable them to assert that the variants have already been validated).

**Comment by reece** [comment]
Marked as a bug because we should aim to catch invalid variants before projection and because it results in an inscrutable exception.

**Comment by icebert** [comment]
fixed in PR #427
