### ISSUE TITLE
get hgvs notation for variant like chr1:12345:A>G

### ISSUE THREAD

**Issue by yujiang02** [biocommons/hgvs#434]
Is there any way I can directly input a variant with chromosme, postion, reference allele and alternative allele and then compute the hgvs notation for this variant?

**Comment by reece** [comment]
Sorry for the delay in replying. 

There's no way currently to do this, but it would be easy to do so. Where did you get this string?

https://github.com/biocommons/hgvs/blob/master/misc/experimental/vcf-add-hgvs adds hgvs tags to VCF. This would provide a good start.

Also, I recently added #447 to provide interconversion utilities.

**Comment by reece** [comment]
Closing this stale issue. The expression in question isn't valid HGVS. I do agree that another library should/could provide this functionality.
