### ISSUE TITLE
Do Duplications Exist in the BioCommons HGVS PAckage

### ISSUE THREAD

**Issue by Akeeeeshi** [biocommons/hgvs#440]
## Does the HGVS Package recognize duplications?

When there is an insertion that causes a duplication the hgvs_c should be annotated as such and should shift to the most 3' possible position as it isn't clear where the exact insertion is occurring. 
(see reference links [here](http://varnomen.hgvs.org/recommendations/DNA/variant/duplication/) and [here](http://varnomen.hgvs.org/recommendations/DNA/variant/insertion/) on this topic.) 

*Example:**

<img width="726" alt="screen shot 2017-05-23 at 11 09 41 am" src="https://cloud.githubusercontent.com/assets/28007814/26361514/3df21502-3fa9-11e7-959d-9a27f559d8ab.png">

<img width="1013" alt="screen shot 2017-05-23 at 11 09 33 am" src="https://cloud.githubusercontent.com/assets/28007814/26361517/3fccfd2e-3fa9-11e7-9d86-782ae801acf4.png">

HGVS Package Notation: NM_004448.2:2355_2356insCTGCTG
Correct Notation: NM_004448.2:c.2358_2359dupCTGCTG (shifts to the end of the original CTTCTG sequence to be the most 3')

**Comment by icebert** [comment]
Hi Akeeeeshi, you should use AssemblyMapper instead of VariantMapper. The AssemblyMapper would shift the mapped variant to 3' by default.

**Comment by Akeeeeshi** [comment]
Sorry if this is a dumb question but could you provide an example of how to get a handle to the assembly mapper?

**Comment by icebert** [comment]
```
import hgvs.assemblymapper
am = hgvs.assemblymapper.AssemblyMapper(hdp, assembly_name='GRCh37')
am.g_to_c(v, "NM_004448.2")
```

For further usage, you can refer to the example in [README](https://github.com/biocommons/hgvs/blob/master/README.rst) and the [docs](http://hgvs.readthedocs.io/en/latest/).
