### ISSUE TITLE
Implement hgvs babelfish: hgvs ↔ {vcf, vmc, spdi, beacon, brcaexchange}

### ISSUE THREAD

**Issue by reece** [biocommons/hgvs#447]
There are several alternative variant formats. This issue intends to implement a module to facilitate conversions between those and the hgvs data model.

Planned formats:
* vcf
* [vmc](https://github.com/ga4gh/vmc)
* spdi
* beacon
* brcaexchange

Considerations:
* How to support assemblies? I'm loathe to emit strings like `chr1:1234:A>T` because they're underspecified.
* VCF should be 5'-shuffled

**Comment by reece** [comment]
See hgvs.extras.babelfish.py (created for #243).

**Comment by lazobax** [comment]
For people finding this who are unfamiliar with the codebase or are beginner coders, let me save you some time.

Huge thanks for @davmlaw and the rest of the team for finally implementing the hgvs to vcf conversion, god knows it was painful to do it manually in 2021. Glad to have found this now. 

If you want to get straight to converting, do this: 

1.  copy the `hgvs/src/hgvs/extras/babelfish.py` file locally. 
2. add the following to it:

``` 
if __name__ == "__main__":
    import sys
    import hgvs.dataproviders.uta 
    from hgvs.exceptions import HGVSError

    assembly_name = sys.argv[1]
    hgvs_str = sys.argv[2]
    hp = hgvs.parser.Parser()
    var_g = hp.parse_hgvs_variant(hgvs_str)
    hdp = hgvs.dataproviders.uta.connect()
    bf = Babelfish(hdp, assembly_name)
    vals = bf.hgvs_to_vcf(var_g)
    print(vals)
```
3. call the script like this `python3 babelfish.py <assembly_name> <HGVS_var>` and it should print the vcf fields you need to the terminal. A list of valid assembly names can be found at `hgvs/lib/python3.12/site-packages/bioutils/_data/assemblies` locally. 

This is a sloppy attempt at getting it to work fast which is what a lot of you will be looking for if you end up here. However, it's better to just instantiate it as an object in your main script. 

I will also be testing this further to see if it's robust. We need more cross-format compatibility in the field.
