### ISSUE TITLE
What is best way to check for a synonymous p. variant?

### ISSUE THREAD

**Issue by lawrlee** [biocommons/hgvs#455]
In hgvs>=1.0.0, what is the correct assertion to check if a `SequenceVariant` object is a synonymous mutation?

For example `NP_001182502.1:p.(Pro1729=)`. When parsed into the object `p`

```
In [21]: p.posedit.pos
Out[21]: Interval(start=Pro1729, end=Pro1729, uncertain=False)

In [22]: p.posedit.edit
Out[22]: AARefAlt(ref=u'', alt=u'', uncertain=False)
```

would a reasonable check be 

```
p.posedit.pos.start == p.posedit.pos.end
```

or 

```
p.posedit.edit.alt == ''
```

or something else?

**Comment by reece** [comment]
Well, that's a fine question indeed.

I think the best way (right now) is something like:
`synonymous = v.type == 'p' and str(v.posedit.edit) == "="`

For example:
```
>>> var_c = hp.parse_hgvs_variant("NM_006158.4:c.1416T>C")
>>> var_p = am38.c_to_p(var_c)
>>> var_p.posedit
PosEdit(pos=Ser472, edit==, uncertain=True)
>>> synonymous = var_p.type == 'p' and str(var_p.posedit.edit) == "="
>>> synonymous
True
```

Also, note that a parsed synonymous variant (as opposed to one generated by projection) has the same structure: 
```
>>> var_p2 = hp.parse_hgvs_variant(str(var_p))
>>> var_p2.posedit
PosEdit(pos=Ser472, edit==, uncertain=True)
```

However, I'd generally like to discourage people from peeking too much into structures. Obviously, it's good that they can, but perhaps we should include methods that provide high-level interpretations, such as a `is_synonymous()` on a posedit. Comments?

@icebert Do you have any recommendations?

**Comment by lawrlee** [comment]
+1 for high-level properties/methods that encapsulate frequently calculated variant types. We write our own (fragile) code to calculate these types:

frameshift
duplication
substitution
insertion
deletion
silent/synonymous

where such code is bound to break whenever the `SequenceVariant` internals change. It would be great to tie them together.

**Comment by icebert** [comment]
The edit classes in hgvs for protein variants have the type method, so I think a better way to assert whether a p. variant is silent is to use `p.posedit.edit.type == "identity"`. For other type of protein variants, the type method is also available, for example `p.posedit.edit.type == "fs"` to assert whether the variant is frameshift variant.
