### ISSUE TITLE
MD5 sums returning instead of protein identifiers

### ISSUE THREAD

**Issue by PeteCausey-Freeman** [biocommons/hgvs#458]
Hi all,

Just to make you aware, after updating to UTA uta_20170707 I have noticed instances where c_to_p mapping is returning MD5s. I have also updated to hgvs 1.1.0.post1. 

A few examples.
NM_001352420.1:c.-108-7C>T  - MD5_7feac51da3b0416f296e7509d50fbf9a:p.?
NM_001258222.2:c.10-47053_10-47048del  -  MD5_97147448e7cdbbf318cc2ec45cf67412:p.?
NM_001346899.1:c.2101_2115del  -  MD5_77fb23b4a66d48ed667fb181fdabdda3:p.(Glu701_Ala705del)
NM_001346898.1:c.2236_2250del - MD5_1a363a2c10ae45372bfc3a44b81e8f6d:p.(Glu746_Ala750del)
NM_001346900.1:c.2077_2091del - MD5_9a8755d460c0ab4397eca0f111624263:p.(Glu693_Ala697del)

Thanks
Pete

**Comment by reece** [comment]
Yuk. Thanks for the report. This is definitely a UTA issue. I'm going to move it over there.

**Comment by reece** [comment]
These are all extremely recent accessions. In fact, 4 of 5 are .1 accessions that were officially released *after* the July 7 data dump that was used to build UTA. (I don't understand how records released in late July and Aug would appear on downloads on July 7, but that is indeed what happened.) As a result, NCBI apparently didn't have NM-NP associations for these, and thus they're absent from UTA.

hgvs translates the cdna into a protein sequence. A table of NM-NP pairs is used to find the corresponding protein sequence accession. If none exists, the MD5 of the sequence is used as a pseudo accession.

I suspect this issue will go away after the next UTA build. I'm going to close this for now. Please reopen if it's not fixed after the next UTA build.

**Comment by PeteCausey-Freeman** [comment]
Fair enough,

I did notice they were all new transcripts. I prefer a MD5 return to an error so actually it's a useful fall back position.

I'll check it goes away at the next UTA release.

Cheers

Pete
