### ISSUE TITLE
Question about hgvs_g to hgvs_c converstion

### ISSUE THREAD

**Issue by akeeeshi** [biocommons/hgvs#471]
Example:

```
In [5]: >>> var_g = hp.parse_hgvs_variant("NC_000013.10:g.32929387T>C")

In [6]: >>> var_c = vm.g_to_c(var_g, "NM_000059.3")
INFO:biocommons.seqrepo.fastadir.fastadir:Opening for reading: /Users/admin/code/knowledge/seqrepo/20161213/sequences/2016/0824/050333/1472015013.075431.fa.bgz

In [7]: str(var_c)
Out[7]: 'NM_000059.3:c.7397='
```

I would expect the c_dot in this instance to be NM_000059.3:c.7397T>C . I am confused as to why the hgvs package is calling this a synonymous variant.

**Comment by akeeeshi** [comment]
Note: I am using seqrepo alongside the hgvs package as well.

**Comment by PeteCausey-Freeman** [comment]
Hi Akeeshi,

This is an instance where the genomic sequence differs from the overlapping transcript reference sequence. I manually checked the reference sequence of NM_000059.3 and variant description NM_000059.3:c.7397C= is correct. This is also  confirmed by mapping to the RefSeqGene
NG_012772.3:g.44771C= and LRG LRG_293:g.44771C=. Such discrepancies are not uncommon (usually common SNPs) , but are overlooked by most analytical tools like VEP.

Cheers

Pete
________________________________

**Comment by akeeeshi** [comment]
Thank you for the clear and well-research explanation! Appreciate it!

**Comment by PeteCausey-Freeman** [comment]
No problem

Cheers
________________________________
