### ISSUE TITLE
Mapping result of stop insertion not compliant with HGVS recommendation

### ISSUE THREAD

**Issue by ianfab** [biocommons/hgvs#474]
When mapping a variant that leads to the insertion (delins/ins) of a stop codon, but where the stop is not at the first position of the inserted amino acid sequence, it results in something like:
input: `print(am37.c_to_p(hp.parse_hgvs_variant('NM_080877.2:c.1733_1735delinsTTT')))`
output: `NP_543153.1:p.(Pro578_Gln598del)`

According to the [HGVS recommendations for protein level delins](http://varnomen.hgvs.org/recommendations/protein/variant/delins/) this is not a valid description of the variant (although it correctly describes the biological consequences):

> p.(Pro578_Lys579delinsLeuTer)
>     the predicted change at the protein level resulting from DNA variant c.1733_1735delinsTTT is a deletion of amino acids Pro578 and Lys579 replaced with LeuTer
>     NOTE: the predicted consequence of variant c.1732_1794del is p.(Pro578_Gln598del). Although the proteins resulting from the changes c.1733_1735delinsTTT and c.1732_1794del are identical, their HGVS description is different. Example derives from the SLC34A3 gene, coding DNA reference sequence NM_080877.2)

So I think that the result of the above mentioned mapping should be
`NP_543153.1:p.(Pro578_Lys579delinsLeuTer)` instead of `NP_543153.1:p.(Pro578_Gln598del)`.

**Comment by reece** [comment]
Bug confirmed, and still exists in 1.2.2.

**Comment by PeteCausey-Freeman** [comment]
Hi Reece,

I have done some digging, and I think that this bug is related to bug 492. Just a pointer which I hope may be helpful. Let me know if you want any working.

Thanks

Pete

**Comment by ianfab** [comment]
In order to resolve this, I think it is necessary to change https://github.com/biocommons/hgvs/blob/88e01d48e9bfd23bf94e90db5d7202aadc8c99d8/hgvs/utils/altseqbuilder.py#L64-L66 otherwise the required information (namely, that the sequence after the inserted stop is retained) is already lost before generating the variant symbol.

This is perhaps a consequence of the module being designed to conform to 

> descriptions at RNA/protein level should describe the changes observed on that level (RNA/protein) and not try to incorporate any knowledge regarding the change at DNA-level

whereas the nomenclature itself makes an exception in this case.
