### ISSUE TITLE
Dups at the End of a Transcript

### ISSUE THREAD

**Issue by akeeeshi** [biocommons/hgvs#476]
`hp.parse_hgvs_variant('NM_001051.2:c.1257dupG')`
`var_c = hp.parse_hgvs_variant('NM_001051.2:c.1257dupG')`
`vm.c_to_p(var_c)`

leads to the following "String Index Out of Range" Error to be thrown.

<img width="1165" alt="screen shot 2017-12-20 at 4 57 14 pm" src="https://user-images.githubusercontent.com/19749361/34230697-edf0c7e8-e5a6-11e7-8ea2-bc62f0596e9a.png">

This variant has an hgvs_g of NC_000022.10:g.37602586dupC and is a dup found at the very last position of the transcript. As seen in UCSC here. 

<img width="1348" alt="screen shot 2017-12-20 at 4 10 40 pm" src="https://user-images.githubusercontent.com/19749361/34230732-1d2df3e6-e5a7-11e7-823b-d0c61bfdbd7a.png">

My understanding is that with 3' shifting this variant would be shifted out of CDS but then should just not have an hgvs_p instead of throwing an error if I'm not mistaken. Is this expected behavior or is there some crucial context that I am missing?

**Comment by reece** [comment]
Yes, this appears to be a bug. Thanks for the clear research into causes. 

We'll include this in the next bug fix release (no ETA right now).
