### ISSUE TITLE
Unpin attrs again

### ISSUE THREAD

**Issue by naomifox** [biocommons/hgvs#488]
We had to temporarily pin the `attrs` version to <17.3.0 due to a bug in that version (https://github.com/biocommons/hgvs/issues/473).  

As of pytest 3.5.0, the minimum version of `attrs` was set to >=17.4.0

Therefore, we should the attrs version now assuming the bug was fixed in 17.4.0

**Comment by reece** [comment]
Simply unpinning doesn't work. The behavior change (bug?) between attrs versions is caused by the use of attrs within closures. (These were introduced by someone else in an early version of the code.)
