### ISSUE TITLE
Questions about the output of hgvs position converter

### ISSUE THREAD

**Issue by xiaoqiwang19** [biocommons/hgvs#489]
Recently,I am using the hgvs python package to manipulate the HGVS variants.I found that some of the results are different from the expected ones. 
For example,I want to manipulate "NM_024426.4:c.1137_1141dup" with the hgvs package and the  position converter results are:
NM_024426.4: c.1137_1141dup
NC_000011.9: g.32417913_32417917dup
According to sequence comparison, the expected position converter results should be as follows:
NC_000011.9: g.32417911_32417915dup
This transcript is negative and according to HGVS recommendations 3' rule, I think the result of latter seem to be more accurate.
What causes this difference ?

**Comment by reece** [comment]
The correct location is NC_000011.9:g.32417913_32417917dup. Mutalyzer is incorrect in this case.

On NM_024426.4, the dup is correctly normalized in the 3' direction. The coordinates are initially projected to NC_000011.9:g.32417911_32417915dup. However, that variant is not properly normalized (3' shifted). The dup sequence (on the + strand) is ACCGT and the trailing sequence is ACAAG… . That means that the dup must be shifted right by the common prefix (AC), to result in NC_000011.9:g.32417913_32417917dup.

In other words, inserting ACCGT after 32417915 (NC_000011.9:g.32417911_32417915dup) has the same net effect as inserting CGTAC after 32417917 (NC_000011.9:g.32417913_32417917dup). The latter is correctly normalized. 

```
In [3]: print(variant_context_w_alignment(am37, v, margin=3))
                                  *****         NC_000011.9:g.32417913_32417917dup
   NC_000011.9  g   32417910 > GACCGTACAAG     > 32417920 NC_000011.9:g.32417913_32417917dup
   NC_000011.9  g   32417910 < CTGGCATGTTC     < 32417920 NC_000011.9:g.32417913_32417917dup
                               |||||||||||       11= 
   NM_024426.4  n       1332 < CTGGCATGTTC     <     1322 NM_024426.4:n.1327_1331dup
   NM_024426.4  c       1142 <                 <     1132 NM_024426.4:c.1137_1141dup
```
