### ISSUE TITLE
Incorrect handling of c_to_p for inversions expressed as delins

### ISSUE THREAD

**Issue by PeteCausey-Freeman** [biocommons/hgvs#492]
Hi Reece and Meng,

I'm running hgvs 1.1.2. I have tried to perform c_to_p mappings for several inversions but formatted as delins objects e.g. NM_001034853.1:c.2847_2848delAGinsCT (which should be NM_001034853.1:c.2847_2848inv). c_to_p generates NP_001030025.1:p.(Glu949_Lys1152delinsAsp) which can't be right. The correct p. should be p.(Glu949_Glu950delinsAspTer). 

I have tried variantmapper as well as assembly mapper and had the same result. 

Is this part of a known problem that prevents c_to_p mapping of inversions, or would you have expected this to work correctly?

Thanks

Pete

**Comment by reece** [comment]
I agree that this looks a little fishy and needs investigation.

```
############################################################################
hgvs-shell -- interactive hgvs
hgvs version: 1.2.3.dev2+h147c7399f094.d20180809
data provider url: postgresql://anonymous:anonymous@localhost/uta_dev/uta_20170117
schema_version: 1.1
data_version: uta_20170117
sequences source: local (SeqRepo)

>>> v = hp.parse_hgvs_variant("NM_001034853.1:c.2847_2848delAGinsCT")
>>> vn = hn.normalize(v)
>>> str(v), str(vn)
('NM_001034853.1:c.2847_2848delinsCT', 'NM_001034853.1:c.2847_2848inv')
>>> p = am37.c_to_p(v)
>>> pn = am37.c_to_p(vn)
>>> str(p), str(pn)
('NP_001030025.1:p.(Glu949_Lys1152delinsAsp)', 'NP_001030025.1:p.(Glu949_Lys1152delinsAsp)')
```
