### ISSUE TITLE
Wrong projection of variants within alignment gap

### ISSUE THREAD

**Issue by icebert** [biocommons/hgvs#495]
Context:
```
            50378561  50378566
                |       |
NC_000019.10    GGA---AAC
NM_007121.5     GGAAACAAC
                |       |
               793     801
```

|  type   |             variant                |  hgvs projected variant (n->g, normalize=False) |              expected variant               |     note     |
|---------|------------------------------------|-------------------------------------------------|---------------------------------------------|--------------|
| within  |  NM_007121.5:n.797A>T              |   NC_000019.10:g.50378564_50378563delinsT       |  NC_000019.10:g.50378563_50378564insATC     |  bug         |
|         |  NM_007121.5:n.797del              |   NC_000019.10:g.50378564_50378563del           |  NC_000019.10:g.50378563_50378564insAC      |  bug         |
|         |  NM_007121.5:n.796_797insT         |   NC_000019.10:g.50378564_50378563insT          |  NC_000019.10:g.50378563_50378564insATAC    |  bug         |
|         |                                    |                                                 |                                             |              |
| exact   |  NM_007121.5:n.796_798=            |   NC_000019.10:g.50378564_50378563delinsAAC     |  NC_000019.10:g.50378563_50378564insAAC     |  bug         |
|         |  NM_007121.5:n.796_798del          |   NC_000019.10:g.50378564_50378563del           |  NC_000019.10:g.50378563_50378564=          |  bug         |
|         |  NM_007121.5:n.796_798delinsTCGG   |   NC_000019.10:g.50378564_50378563delinsTCGG    |  NC_000019.10:g.50378563_50378564insTCGG    |  bug         |
|         |                                    |                                                 |                                             |              |
| partial |  NM_007121.5:n.795_796del          |   NC_000019.10:g.50378563del                    |  NC_000019.10:g.50378563delinsAC            |  bug         |
|         |  NM_007121.5:n.795_796delinsTT     |   NC_000019.10:g.50378563delinsTT               |  NC_000019.10:g.50378563delinsTTAC          |  bug         |
|         |  NM_007121.5:n.795_796insT         |   NC_000019.10:g.50378563insT                   |  NC_000019.10:g.50378563_50378564insTAAC    |  bug         |
|         |                                    |                                                 |                                             |              |
| covers  |  NM_007121.5:n.794_800del          |   NC_000019.10:g.50378562_50378565del           |                                             |  reasonable  |
|         |  NM_007121.5:n.794_800delinsTC     |   NC_000019.10:g.50378562_50378565delinsTC      |                                             |  reasonable  |

Context:
```
           149779572  149779580
                |       |
NC_000007.14    TGACAGCCC
NM_198455.2     TGA---CCC
                |       |
              1113     1118
```

|  type   |             variant                |  hgvs projected variant (n->g, normalize=False) |              expected variant               |     note     |
|---------|------------------------------------|-------------------------------------------------|---------------------------------------------|--------------|
| within  |  NM_198455.2:n.1115_1116insT       |   NC_000007.14:g.149779574_149779578insT        |  NC_000007.14:g.149779575_149779577delinsT  |  bug         |
|         |                                    |                                                 |                                             |              |
| exact   |  NM_198455.2:n.1115_1116insCAG     |   NC_000007.14:g.149779574_149779578insCAG      |  NC_000007.14:g.149779574_149779578=        |  bug         |
|         |  NM_198455.2:n.1115_1116=          |   NC_000007.14:g.149779574_149779578delinsAC    |                                             |  reasonable  |
|         |                                    |                                                 |                                             |              |
| partial |  NM_198455.2:n.1115_1116insCA      |   NC_000007.14:g.149779574_149779578insC        |  NC_000007.14:g.149779575_149779577delinsCA |  bug         |
|         |                                    |                                                 |                                             |              |
| cover   |  NM_198455.2:n.1114_1117del        |   NC_000007.14:g.149779573_149779579del         |                                             |  reasonable  |
|         |  NM_198455.2:n.1114_1117delinsCAG  |   NC_000007.14:g.149779573_149779579delinsCAG   |                                             |  reasonable  |

**Comment by reece** [comment]
The above tests are in the `495-fix-projection-at-gap` branch.

**Comment by AngieHinrichs** [comment]
This is a great improvement, congrats!

Regarding the second example:

> NM_007121.5:n.797del | NC_000019.10:g.50378564_50378563del

If NM_007121.5:n.797 is deleted then NM_007121.5 still has two more bases than NC_000019.10 at that locus.  So rather than 50378564_50378563del, wouldn't it be 

```
            50378561  50378566
                |       |
NC_000019.10    GGA---AAC
NM_007121.5     GGAA-CAAC
                |       |
               793     801
```
NC_000019.10:g.50378563_50378564insAC ?

Also regarding 50378564_50378563del, is it kosher HGVS for start to be greater than end?  I assume you mean a 0-base region/point, but HGVS doesn't really have a concept for that aside from point insertions which they make into a 2-base region.

**Comment by reece** [comment]
@AngieHinrichs: `start > end` is never kosher. In that text, we were pointing out that hgvs 1.1.3 give the *wrong* result. 

Meng has just submitted a PR that I'm reviewing now to fix all of these cases.

Meng's contributions to the hgvs package are exemplary and invaluable!
