### ISSUE TITLE
Investigate why Python 3 tests take 2x time over Python 2 tests

### ISSUE THREAD

**Issue by reece** [biocommons/hgvs#506]
Py 3 testing takes apx twice as long as Py2 testing. 

For example, see https://travis-ci.org/biocommons/hgvs/builds/407297568. Py 2.7 took 3:03, 3.5 took 5:55, 3.6 too 6:50. These numbers appear representative. Running the tests with --durations=0 shows that all tests are inflated by 2x (rather than just a few tests). 

@icebert Any ideas?

**Comment by xiucz** [comment]
But still, I prefer python3 more.

**Comment by reece** [comment]
I've attached a timing script and sample input that I used.

[timing.zip](https://github.com/biocommons/hgvs/files/2490118/timing.zip)

**Comment by reece** [comment]
Now that the Py2 version is dead, the comparison is irrelevant.
However, we should profile sometime to look for optimizations.
