### ISSUE TITLE
how to convert annovar result to hgvs format

### ISSUE THREAD

**Issue by xiucz** [biocommons/hgvs#509]
When I  annotate a vcf with annovar software, the results are like below:
```
NM_001313896.1:c.344_349dup
```
or 
```
MEGF6:NM_001409:exon8:c.C938T:p.A313V
```

Is there a way to convert `NM_001409:c.C938T` to `NM_001409:c.938C>T` in your python model ?

thank you.

**Comment by reece** [comment]
Currently, there's no way to do this.

It would be simple to add new rules to the grammar. The main reason for not doing so is that it would imply that such expressions are valid HGVS (they're not).

My recommendation is that you ask the annovar folks to emit legit HGVS. If you need to deal with these expressions in the meantime, a simple regexp rewrite would suffice. Try this:
```python
>>> import re
>>> def rewrite_hgvs(hvar):
...     return re.sub(r"c.(\w)(\d+)(\w)", r"c.\2\1>\3", hvar)

# rewrite the a bogus hgvs expression like c.C938T as c.938C>T
>>> rewrite_hgvs("NM_001409:c.C938T")
'NM_001409:c.938C>T'

# non-matching expressions are not affected, e.g., 
>>> rewrite_hgvs("NM_001409:c.938C>T")
'NM_001409:c.389>C>T'
```

**Comment by xiucz** [comment]
@reece 
Thank you， maybe it is the simplest way to solve it. I did not use RegEx for the concern that I did not take something into consideration. Thanks for your advice.
