### ISSUE TITLE
refresh hgvs packages of PyPI

### ISSUE THREAD

**Issue by xiaoqiwang19** [biocommons/hgvs#512]
When I used HGVS, I also encountered an error using the function of am.c_to_p(var_c) if  var_c  is  the type of  inv. I see that you have corrected the bug. c_to_p still doesn't support inv，when hgvs installed  by pip method.HGVS only was updated based the bug  on github, but not updated in PIPY libray. Could you please update HGVS in  the pypi library? For some reason, I can only install it with pip .Thank you.

**Comment by reece** [comment]
Just pushed 1.2.2 (https://pypi.org/project/hgvs/) with inv support.
