### ISSUE TITLE
g_to_c fails for Repeat variant

### ISSUE THREAD

**Issue by andreas-invitae** [biocommons/hgvs#524]
Hi,

I have a repeat-variant. When I try to run g_to_c this fails with:

``` 
"/usr/local/lib/python2.7/dist-packages/hgvs/variantmapper.py", line 215, in g_to_c
     var_g.fill_ref(self.hdp)
   File "/usr/local/lib/python2.7/dist-packages/hgvs/sequencevariant.py", line 54, in fill_ref
     if type in ["del", "delins", "identity", "dup", "repeat"] and self.posedit.edit.ref_s is None:
 AttributeError: 'Repeat' object has no attribute 'ref_s'
```
Is this a bug or a not-implemented feature? ( I am on hgvs 1.2.3)

Thanks!

Andreas

**Comment by reece** [comment]
Although the Repeat class exists, repeats are unimplemented (#113). There are no parsing rules or tests for repeats. You must have manually created this repeat.

Given that #113 exists, I'm going to close this issue.
