### ISSUE TITLE
UTA access through a proxy

### ISSUE THREAD

**Issue by marc-sturm** [biocommons/hgvs#530]
Hi,

is there a way to access UTA trough an authentificating proxy?

The proxy data is in the environment:
> http_proxy=http://user:password@host:port
> https_proxy=http://user:password@host:port
> ftp_proxy=http://user:password@host:port
> HTTP_PROXY=http://user:password@host:port
> HTTPS_PROXY=http://user:password@host:port
> FTP_PROXY=http://user:password@host:port

I try to execute
> import hgvs.parser
> import hgvs.dataproviders.uta
> 
> hgvs_c = 'NM_001637.3:c.1582G>A'
> 
> hdp = hgvs.dataproviders.uta.connect()
> am = hgvs.assemblymapper.AssemblyMapper(hdp, assembly_name='GRCh37', alt_aln_method='splign', replace_reference=True)

and get the following error:
> python test.py
> Traceback (most recent call last):
>   File "test.py", line 9, in <module>
>     am = hgvs.assemblymapper.AssemblyMapper(hdp, assembly_name='GRCh37', alt_aln_method='splign', replace_reference=True)
>   File "/usr/local/lib/python2.7/dist-packages/hgvs/dataproviders/uta.py", line 107, in connect
>     conn = UTA_postgresql(url=url, pooling=pooling, application_name=application_name, mode=mode, cache=cache)
>   File "/usr/local/lib/python2.7/dist-packages/hgvs/dataproviders/uta.py", line 477, in __init__
>     super(UTA_postgresql, self).__init__(url, mode, cache)
>   File "/usr/local/lib/python2.7/dist-packages/hgvs/dataproviders/uta.py", line 198, in __init__
>     self._connect()
>   File "/usr/local/lib/python2.7/dist-packages/hgvs/dataproviders/uta.py", line 508, in _connect
>     self._conn = psycopg2.connect(**conn_args)
>   File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 130, in connect
>     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> psycopg2.OperationalError: could not connect to server: Connection timed out
>         Is the server running on host "uta.biocommons.org" (54.146.81.237) and accepting
>         TCP/IP connections on port 5432?

Thanks,
  Marc

**Comment by reece** [comment]
Hi @marc-sturm: The postgresql connection *requires* TCP/IP access to port 5432. That won't work with your proxies. The only recourse in your case is to install UTA (and, ideally, SeqRepo) locally. The easiest way to do that is to use the docker images. Please see the installation instructions for details.

A long-standing desire is to replace the postgresql interface with a REST-based connection (via https), but that's not available at this time.

Good luck,
Reece
