### ISSUE TITLE
seqrepo ：maintain a local sequence database

### ISSUE THREAD

**Issue by xiaoqiwang19** [biocommons/hgvs#531]
I had some questions when I installed the SeqRepo database locally.
I set the database path after downloading the database.
export HGVS_SEQREPO_DIR=/DATA/wangxiaoqi/software/seqrepo/2018-10-03
There is a  exception occurred when I tried to use hgvs:
>>> import hgvs.parser
replace_reference=True)
hn = hgvs.normalizer.Normalizer(hdp)>>> hp = hgvs.parser.Parser()
>>> import hgvs.normalizer
>>> import hgvs.dataproviders.uta
>>> import hgvs.assemblymapper
>>> hdp = hgvs.dataproviders.uta.connect()
>>> am = hgvs.assemblymapper.AssemblyMapper(hdp,assembly_name='GRCh37', alt_aln_method='splign',replace_reference=True)
>>> hn = hgvs.normalizer.Normalizer(hdp)
>>> c1=hp.parse_hgvs_variant('NM_000059.3:c.7612A>G')
>>> c1n = hn.normalize(c1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/DATA/wangxiaoqi/software/anaconda2/envs/hgvs_py2_20181022/lib/python2.7/site-packages/hgvs/normalizer.py", line 80, in normalize
    var = self.hm.c_to_n(var)
  File "/DATA/wangxiaoqi/software/anaconda2/envs/hgvs_py2_20181022/lib/python2.7/site-packages/hgvs/variantmapper.py", line 289, in c_to_n
    self._validator.validate(var_c)
  File "/DATA/wangxiaoqi/software/anaconda2/envs/hgvs_py2_20181022/lib/python2.7/site-packages/hgvs/validator.py", line 33, in validate
    return self._ivr.validate(var, strict) and self._evr.validate(var, strict)
  File "/DATA/wangxiaoqi/software/anaconda2/envs/hgvs_py2_20181022/lib/python2.7/site-packages/hgvs/validator.py", line 74, in validate
    raise HGVSInvalidVariantError(msg)
hgvs.exceptions.HGVSInvalidVariantError: NM_000059.3:c.7612A>G: Variant reference (A) does not agree with reference sequence (D)

But when I don't use a localized seqrepo database, the results are normal.There is no exception occurred .
>>> c1=hp.parse_hgvs_variant('NM_000059.3:c.7612A>G')
>>> c1n = hn.normalize(c1)
>>> str(c1n)
'NM_000059.3:c.7612A>G'

I don't know where I did wrong.I hope you can give me some guidance and advice.

**Comment by reece** [comment]
@xiaoqiwang19 Yikes! This is very odd.

I'm unable to reproduce this. Here's what I see:

```
$ hgvs-shell
In [1]: str(hdp)
Out[1]: 'UTA_postgresql <data_version:uta_20170117; schema_version:1.1; application_name=hgvs-shell; url=postgresql://anonymous:anonymous@localhost/uta_dev/uta_20170117; sequences-from=seqfetcher>'

In [2]: str( hn.normalize( hp.parse_hgvs_variant('NM_000059.3:c.7612A>G') ) )
Out[2]: 'NM_000059.3:c.7612A>G'

$ HGVS_SEQREPO_DIR=/usr/local/share/seqrepo/2018-10-03  hgvs-shell
In [1]: str(hdp)
Out[1]: 'UTA_postgresql <data_version:uta_20170117; schema_version:1.1; application_name=hgvs-shell; url=postgresql://anonymous:anonymous@localhost/uta_dev/uta_20170117; sequences-from=/usr/local/share/seqrepo/2018-10-03>'

In [2]: str( hn.normalize( hp.parse_hgvs_variant('NM_000059.3:c.7612A>G') ) )
Out[2]: 'NM_000059.3:c.7612A>G'

```

`str(hdp)` will show where sequences are coming from: seqfetcher in the first case, and seqrepo 2018-10-03 in the second.


Okay. That makes me feel better. Now, let's figure out why you're getting this result. Please do this:

```
$ export HGVS_SEQREPO_DIR=/DATA/wangxiaoqi/software/seqrepo/2018-10-03
$ hgvs-shell
In [2]: seq = hdp.seqfetcher.fetch_seq("NM_000059.3")

In [3]: "D" in seq
Out[3]: False
```

Obviously, if you get True on the last line, we've got a problem.

Please also send your platform: Which OS? What Python version?

**Comment by xiaoqiwang19** [comment]
export HGVS_SEQREPO_DIR=/DATA/wangxiaoqi/software/seqrepo/2018-10-03
hgvs-shell
INFO:root:Starting hgvs-shell 1.2.4
INFO:biocommons.seqrepo:biocommons.seqrepo 0.4.2
INFO:hgvs.dataproviders.seqfetcher:Using SeqRepo(/DATA/wangxiaoqi/software/seqrepo/2018-10-03) sequence fetching
Python 2.7.15 | packaged by conda-forge
In [1]:  seq = hdp.seqfetcher.fetch_seq("NM_000059.3")
INFO:biocommons.seqrepo.fastadir.fastadir:Opening for reading: /DATA/wangxiaoqi/software/seqrepo/2018-10-03/sequences/2016/0824/050333/1472015013.075431.fa.bgz

In [2]: "D" in seq
Out[2]: True

In [3]: str(hdp)
Out[3]: 'UTA_postgresql <data_version:uta_20170117; schema_version:1.1; application_name=hgvs-shell; url=postgresql://anonymous@SGE-SERVER:15032/uta/uta_20170117; sequences-from=/DATA/wangxiaoqi/software/seqrepo/2018-10-03>'

My OS is Ubuntu 16.04.4 LTS and  Python version is 2.7.15.

**Comment by reece** [comment]
Okay. Please update pysam. I remember a bug around that version that caused
pysam to incorrectly fetch sequences in compressed files.

pip install pysam -U  should do it.
