### ISSUE TITLE
installed hgvs in conda virtual env, performed ipykernel install, but import hgvs in jupyter notebook didn't work

### ISSUE THREAD

**Issue by Deena-B** [biocommons/hgvs#543]
I'm noting my steps here with the hope of integrating this workflow into the docs.

I am using anaconda (version 1.7.2) on a macOS High Sierra (version 10.13.6)

In a terminal that opens up to the conda "base" environment:

Create a virtual environment called "biocommons"
`conda create -n biocommons_stable`

Activate your biocommons virtual environment
`conda activate biocommons_stable`

Install pip
`conda install pip`

Install postgresql
`conda install -c anaconda postgresql`

Install hgvs
`pip install hgvs`

Red text that appears during installation:
- Numerical Python (NumPy) is not installed, therefore, failed to build biopython.
- kaggle 1.5.0 requires python-dateutil, which is not installed.

Test your installation
`hgvs-shell`

In [1]: `v = hp.parse_hgvs_variant("NM_033089.6:c.571C>G")`

In [2]: `am37.c_to_g(v)`
Out[2]: SequenceVariant(ac=NC_000020.10, type=g, posedit=278801C>G)

In [3]: `am38.c_to_g(v)`
Out[3]: SequenceVariant(ac=NC_000020.11, type=g, posedit=298157C>G)

Exit the hgvs-shell
ctrl+d 

Deactivate the biocommons_stable virtual env
`conda deactivate`

Create a biocommons kernel for jupyter notebooks 
`python -m ipykernel install --user --name biocommons_stable --display-name "biocommons_stable"`
- `--name biocommons_stable` tells it to install the biocommons_stable virtual env 
- `--display-name "..."` is what the kernal is referenced as in a jupyter notebook

Open a jupyter notebook
`jupyter notebook`

In your notebook:

Change the Kernal to "biocommons_stable"

`import hgvs`
Error: ModuleNotFoundError: No module named 'hgvs'

`hgvs-shell`
NameError: name 'hgvs' is not defined

**Comment by Deena-B** [comment]
The reason that I could not `import hgvs` from a Jupyter Notebook (JN) was because I tried to make the kernel outside of the env. Instead, I needed to create the kernel within the env, which meant I needed to install jupyter (which includes ipykernel) in my env. By stipulating `--user`, I can use the kernel from the jupyter notebook version that I have installed within my current user, rather than having to start jupyter notebooks from within my env. Using my 'user' installed JN, rather than my env installed JN, allows me to access multiple env-specific kernels in one JN session.

Of course it wasn't this clear cut to figure out my problem, because when I tried to install a kernel within my new env, I got the error below:

ImportError: cannot import name 'create_prompt_application' from 'prompt_toolkit.shortcuts'

It turns out that this error is because prompt_toolkit v2.0 had an api breaking change. Therefore, I needed to install prompt_toolkit with a version <2.0.0 and >=1.0.15.

I found that others had done this with the following command:
`pip install 'prompt-toolkit<2.0.0,>=1.0.15' --force-reinstall`

But, as you'll see in my process below, I used conda (rather than pip) to specify the version.


**Follow the steps below to install hgvs in a conda virtual env, create an ipython kernel and test your install in the command line and in a Jupyter Notebook:** 

See a list of your conda virtual environments
`conda info --envs`

Delete any virtual environments with the name you want to use
`conda remove --name biocommons_stable --all -y`

Ensure the deletion worked
`conda info --envs`

Create, then activate a new, Python3-based virtual env
`conda create -n biocommons_stable -y`
`conda activate biocommons_stable`

Install pip
`conda install pip -y`

Install postgresql
`conda install -c anaconda postgresql -y`

Install hgvs
`pip install hgvs`

Use a program that was installed with hgvs, called 'hgvs-shell' to test your install using the command line
`hgvs-shell`

Ensure you get the outputs from the inputs
In [1]: v = hp.parse_hgvs_variant("NM_033089.6:c.571C>G")

In [2]: am37.c_to_g(v)
Out[2]: SequenceVariant(ac=NC_000020.10, type=g, posedit=278801C>G)

In [3]: am38.c_to_g(v)
Out[3]: SequenceVariant(ac=NC_000020.11, type=g, posedit=298157C>G)

type: "ctrl^d" to exit iPython

Install Jupyter
`conda install jupyter -y`
- note that the version of prompt_toolkit is 2.0

Downgrade prompt_toolkit
`conda install "prompt_toolkit<2.0.0,>=1.0.15"`

Create an environment kernel for Jupyter Notebooks
`python -m ipykernel install --user --name biocommons_stable --display-name "biocommons_stable"`

Test again
`hgvs-shell` 
Ensure I get these outputs: 
In [1]: v = hp.parse_hgvs_variant("NM_033089.6:c.571C>G")

In [2]: am37.c_to_g(v)
Out[2]: SequenceVariant(ac=NC_000020.10, type=g, posedit=278801C>G)

In [3]: am38.c_to_g(v)
Out[3]: SequenceVariant(ac=NC_000020.11, type=g, posedit=298157C>G)

Type: ctrl^d to exit iPython

Deactivate/exit the virtual environment
`conda deactivate`

Start Jupyter Notebooks - from your user install
`jupyter notebook`

Make a new notebook with biocommons_stable kernel

In the fields of your Jupyter Notebook run the following to test your kernel:

```
hgvs_g = "NC_000007.13:g.36561662C>T"
hgvs_c = "NM_001637.3:c.1582G>A"
hgvs_p = "NP_001628.1:p.(Gly528Arg)"

import hgvs
import hgvs.assemblymapper
import hgvs.dataproviders.uta
import hgvs.normalizer
import hgvs.parser
import hgvs.variantmapper
import hgvs.validator
from hgvs.utils.context import variant_context_w_alignment

hp = hgvsparser = hgvs.parser.Parser()
hdp = hgvs.dataproviders.uta.connect()
vm = variantmapper = hgvs.variantmapper.VariantMapper(hdp)
am37 = easyvariantmapper = hgvs.assemblymapper.AssemblyMapper(hdp, assembly_name='GRCh37')
am38 = easyvariantmapper = hgvs.assemblymapper.AssemblyMapper(hdp, assembly_name='GRCh38')
hv = hgvs.validator.Validator(hdp)
hn = hgvs.normalizer.Normalizer(hdp)

var_g = hgvsparser.parse_hgvs_variant(hgvs_g)
var_c = hgvsparser.parse_hgvs_variant(hgvs_c)
var_p = hgvsparser.parse_hgvs_variant(hgvs_p)
```

Then also run in the cells of your Jupyter Notebook
```
v = hp.parse_hgvs_variant("NM_033089.6:c.571C>G")
am37.c_to_g(v)
```
Should return: SequenceVariant(ac=NC_000020.10, type=g, posedit=278801C>G)

```
am38.c_to_g(v)
```
Should return: SequenceVariant(ac=NC_000020.11, type=g, posedit=298157C>G)

**Comment by Deena-B** [comment]
A few updates to my post above.

1. Using `conda install postgresql -y` to install postgresql 11.1 works :)

2. `conda install jupyter -y` now installs `prompt_toolkit-2.0.9`, which works with ipykernel

**Comment by Deena-B** [comment]
**To setup a conda environment that uses your local version of hgvs perform the following steps:**

See a list of your conda virtual environments
`conda info --envs`

Delete any virtual environments with the name you want to use
`conda remove --name hgvs_local --all -y`

Create, then activate a new, Python3-based virtual env
`conda create -n hgvs_local -y`
`conda activate hgvs_local`

Install setuptools (you don't need to install pip)
`conda install setuptools -y`

Install postgresql
`conda install postgresql -y`

Navigate to the hgvs directory that has the .git file in it and 
make sure you are on your desired branch.

Install hgvs
`make install`
- runs `python setup.py install`
- note that this generated a number of warnings, but still works, see list of warnings below.

Install Jupyter Notebooks
`conda install jupyter -y`

Create an environment kernel for Jupyter Notebooks
`python -m ipykernel install --user --name hgvs_local --display-name "hgvs_local"`

From anywhere inside the hgvs_local venv, 
use the program called 'hgvs-shell' that was installed by 'make install' 
to test your install using the command line:
`hgvs-shell`
then re-enter queries (see above)
- this returned the expected outputs for me, despite all the warnings. 



Warnings generated by running `make install` 
'''
warning: no files found matching 'KNOWN_BUGS'
warning: no files found matching 'THANKS'
no previously-included directories found matching 'tests/'
warning: no files found matching 'samtools/configure'
warning: no files found matching 'samtools/config.mk.in'
warning: no files found matching 'samtools/config.h.in'
bcftools/vcfroh.c.pysam.c:764:32: warning: result of comparison of constant 256 with
      expression of type 'int8_t' (aka 'signed char') is always true
      [-Wtautological-constant-out-of-range-compare]
            case BCF_BT_INT8:  BRANCH(int8_t); break;
                               ^~~~~~~~~~~~~~
bcftools/vcfroh.c.pysam.c:754:34: note: expanded from macro 'BRANCH'
                prob[0] = p[irr] < 256 ? args->pl2p[ p[irr] ] : args->pl2p[255]; \
                          ~~~~~~ ^ ~~~
bcftools/vcfroh.c.pysam.c:764:32: warning: result of comparison of constant 256 with
      expression of type 'int8_t' (aka 'signed char') is always true
      [-Wtautological-constant-out-of-range-compare]
            case BCF_BT_INT8:  BRANCH(int8_t); break;
                               ^~~~~~~~~~~~~~
bcftools/vcfroh.c.pysam.c:755:34: note: expanded from macro 'BRANCH'
                prob[1] = p[ira] < 256 ? args->pl2p[ p[ira] ] : args->pl2p[255]; \
                          ~~~~~~ ^ ~~~
bcftools/vcfroh.c.pysam.c:764:32: warning: result of comparison of constant 256 with
      expression of type 'int8_t' (aka 'signed char') is always true
      [-Wtautological-constant-out-of-range-compare]
            case BCF_BT_INT8:  BRANCH(int8_t); break;
                               ^~~~~~~~~~~~~~
bcftools/vcfroh.c.pysam.c:756:34: note: expanded from macro 'BRANCH'
                prob[2] = p[iaa] < 256 ? args->pl2p[ p[iaa] ] : args->pl2p[255]; \
                          ~~~~~~ ^ ~~~
bcftools/vcfroh.c.pysam.c:794:32: warning: result of comparison of constant 256 with
      expression of type 'int8_t' (aka 'signed char') is always true
      [-Wtautological-constant-out-of-range-compare]
            case BCF_BT_INT8:  BRANCH(int8_t); break;
                               ^~~~~~~~~~~~~~
bcftools/vcfroh.c.pysam.c:784:34: note: expanded from macro 'BRANCH'
                prob[0] = p[irr] < 256 ? args->pl2p[ p[irr] ] : args->pl2p[255]; \
                          ~~~~~~ ^ ~~~
bcftools/vcfroh.c.pysam.c:794:32: warning: result of comparison of constant 256 with
      expression of type 'int8_t' (aka 'signed char') is always true
      [-Wtautological-constant-out-of-range-compare]
            case BCF_BT_INT8:  BRANCH(int8_t); break;
                               ^~~~~~~~~~~~~~
bcftools/vcfroh.c.pysam.c:785:34: note: expanded from macro 'BRANCH'
                prob[1] = p[ira] < 256 ? args->pl2p[ p[ira] ] : args->pl2p[255]; \
                          ~~~~~~ ^ ~~~
bcftools/vcfroh.c.pysam.c:794:32: warning: result of comparison of constant 256 with
      expression of type 'int8_t' (aka 'signed char') is always true
      [-Wtautological-constant-out-of-range-compare]
            case BCF_BT_INT8:  BRANCH(int8_t); break;
                               ^~~~~~~~~~~~~~
bcftools/vcfroh.c.pysam.c:786:34: note: expanded from macro 'BRANCH'
                prob[2] = p[iaa] < 256 ? args->pl2p[ p[iaa] ] : args->pl2p[255]; \
                          ~~~~~~ ^ ~~~
bcftools/vcfroh.c.pysam.c:936:36: warning: result of comparison of constant 256 with
      expression of type 'int8_t' (aka 'signed char') is always true
      [-Wtautological-constant-out-of-range-compare]
                case BCF_BT_INT8:  BRANCH(int8_t); break;
                                   ^~~~~~~~~~~~~~
bcftools/vcfroh.c.pysam.c:931:33: note: expanded from macro 'BRANCH'
                pdg[0] = p[irr] < 256 ? args->pl2p[ p[irr] ] : args->pl2p[255]; \
                         ~~~~~~ ^ ~~~
bcftools/vcfroh.c.pysam.c:936:36: warning: result of comparison of constant 256 with
      expression of type 'int8_t' (aka 'signed char') is always true
      [-Wtautological-constant-out-of-range-compare]
                case BCF_BT_INT8:  BRANCH(int8_t); break;
                                   ^~~~~~~~~~~~~~
bcftools/vcfroh.c.pysam.c:932:33: note: expanded from macro 'BRANCH'
                pdg[1] = p[ira] < 256 ? args->pl2p[ p[ira] ] : args->pl2p[255]; \
                         ~~~~~~ ^ ~~~
bcftools/vcfroh.c.pysam.c:936:36: warning: result of comparison of constant 256 with
      expression of type 'int8_t' (aka 'signed char') is always true
      [-Wtautological-constant-out-of-range-compare]
                case BCF_BT_INT8:  BRANCH(int8_t); break;
                                   ^~~~~~~~~~~~~~
bcftools/vcfroh.c.pysam.c:933:33: note: expanded from macro 'BRANCH'
                pdg[2] = p[iaa] < 256 ? args->pl2p[ p[iaa] ] : args->pl2p[255]; \
                         ~~~~~~ ^ ~~~
9 warnings generated.
pysam/libcutils.c:6272:3: warning: implicit declaration of function 'bcftools_set_stderr'
      is invalid in C99 [-Wimplicit-function-declaration]
  bcftools_set_stderr(__pyx_t_10);
  ^
pysam/libcutils.c:6444:5: warning: implicit declaration of function
      'bcftools_set_stdout_fn' is invalid in C99 [-Wimplicit-function-declaration]
    bcftools_set_stdout_fn(__pyx_t_13);
    ^
pysam/libcutils.c:6455:5: warning: implicit declaration of function 'bcftools_set_stdout'
      is invalid in C99 [-Wimplicit-function-declaration]
    bcftools_set_stdout(__pyx_t_10);
    ^
pysam/libcutils.c:6851:7: warning: implicit declaration of function
      'bcftools_set_stdout_fn' is invalid in C99 [-Wimplicit-function-declaration]
      bcftools_set_stdout_fn(__pyx_t_13);
      ^
pysam/libcutils.c:6991:7: warning: implicit declaration of function 'bcftools_set_stdout'
      is invalid in C99 [-Wimplicit-function-declaration]
      bcftools_set_stdout(__pyx_t_10);
      ^
pysam/libcutils.c:7022:5: warning: implicit declaration of function
      'bcftools_set_stdout_fn' is invalid in C99 [-Wimplicit-function-declaration]
    bcftools_set_stdout_fn(((char const *)"-"));
    ^
pysam/libcutils.c:7287:5: warning: implicit declaration of function 'bcftools_set_optind'
      is invalid in C99 [-Wimplicit-function-declaration]
    bcftools_set_optind(1);
    ^
pysam/libcutils.c:7316:5: warning: implicit declaration of function 'bcftools_set_optind'
      is invalid in C99 [-Wimplicit-function-declaration]
    bcftools_set_optind(0);
    ^
pysam/libcutils.c:7366:22: warning: implicit declaration of function 'bcftools_main' is
      invalid in C99 [-Wimplicit-function-declaration]
    __pyx_v_retval = bcftools_main((__pyx_v_n + 2), __pyx_v_cargs);
                     ^
pysam/libcutils.c:7435:3: warning: implicit declaration of function
      'bcftools_unset_stderr' is invalid in C99 [-Wimplicit-function-declaration]
  bcftools_unset_stderr();
  ^
pysam/libcutils.c:7471:5: warning: implicit declaration of function
      'bcftools_unset_stdout' is invalid in C99 [-Wimplicit-function-declaration]
    bcftools_unset_stdout();
    ^
11 warnings generated.
pysam/libcalignmentfile.c:30112:126: warning: passing 'bam_pileup1_t **' to parameter of
      type 'const bam_pileup1_t **' discards qualifiers in nested pointer types
      [-Wincompatible-pointer-types-discards-qualifiers]
  ...(&__pyx_v_self->pos), (&__pyx_v_self->n_plp), (&__pyx_v_self->plp));
                                                   ^~~~~~~~~~~~~~~~~~~~
/private/var/folders/yp/zwmchy8574l9ktkwljctk_sm0000gn/T/easy_install-_tu3cxaw/pysam-0.15.2/htslib/htslib/sam.h:686:96: note:
      passing argument to parameter 'plp' here
  ...iter, int *_tid, int *_pos, int *n_plp, const bam_pileup1_t **plp);
                                                                   ^
1 warning generated.
pysam/libctabix.c:8706:27: warning: assigning to 'char **' from 'const char **' discards
      qualifiers in nested pointer types
      [-Wincompatible-pointer-types-discards-qualifiers]
        __pyx_v_sequences = tbx_seqnames(__pyx_v_self->index, (&__pyx_v_nsequences));
                          ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pysam/libctabix.c:13977:39: warning: implicit conversion from 'int' to 'int8_t'
      (aka 'signed char') changes value from 65536 to 0 [-Wconstant-conversion]
  __pyx_t_2 = __Pyx_PyInt_From_int8_t(TBX_UCSC); if (unlikely(!__pyx_t_2)) __PYX_E...
              ~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~
/private/var/folders/yp/zwmchy8574l9ktkwljctk_sm0000gn/T/easy_install-_tu3cxaw/pysam-0.15.2/htslib/htslib/tbx.h:41:21: note:
      expanded from macro 'TBX_UCSC'
#define TBX_UCSC    0x10000
                    ^~~~~~~
pysam/libctabix.c:14009:39: warning: implicit conversion from 'int' to 'int8_t'
      (aka 'signed char') changes value from 65536 to 0 [-Wconstant-conversion]
  __pyx_t_3 = __Pyx_PyInt_From_int8_t(TBX_UCSC); if (unlikely(!__pyx_t_3)) __PYX_E...
              ~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~
/private/var/folders/yp/zwmchy8574l9ktkwljctk_sm0000gn/T/easy_install-_tu3cxaw/pysam-0.15.2/htslib/htslib/tbx.h:41:21: note:
      expanded from macro 'TBX_UCSC'
#define TBX_UCSC    0x10000
                    ^~~~~~~
pysam/libctabix.c:14379:43: warning: implicit conversion from 'int' to 'int8_t'
      (aka 'signed char') changes value from 65536 to 0 [-Wconstant-conversion]
      __pyx_t_3 = __Pyx_PyInt_From_int8_t(TBX_UCSC); if (unlikely(!__pyx_t_3)) __P...
                  ~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~
/private/var/folders/yp/zwmchy8574l9ktkwljctk_sm0000gn/T/easy_install-_tu3cxaw/pysam-0.15.2/htslib/htslib/tbx.h:41:21: note:
      expanded from macro 'TBX_UCSC'
#define TBX_UCSC    0x10000
                    ^~~~~~~
4 warnings generated.
pysam/libcbcf.c:33142:18: warning: 'bcf_hdr_fmt_text' is deprecated: use bcf_hdr_format()
      instead [-Wdeprecated-declarations]
  __pyx_v_hstr = bcf_hdr_fmt_text(__pyx_v_self->ptr, 0, (&__pyx_v_hlen));
                 ^
/private/var/folders/yp/zwmchy8574l9ktkwljctk_sm0000gn/T/easy_install-_tu3cxaw/pysam-0.15.2/htslib/htslib/vcf.h:440:9: note:
      'bcf_hdr_fmt_text' has been explicitly marked deprecated here
        HTS_DEPRECATED("use bcf_hdr_format() instead");
        ^
/private/var/folders/yp/zwmchy8574l9ktkwljctk_sm0000gn/T/easy_install-_tu3cxaw/pysam-0.15.2/htslib/htslib/hts_defs.h:65:49: note:
      expanded from macro 'HTS_DEPRECATED'
#define HTS_DEPRECATED(message) __attribute__ ((__deprecated__ (message)))
                                                ^
1 warning generated.
creating /Users/drb/anaconda3/envs/hgvs_local/lib/python3.7/site-packages/pysam-0.15.2-py3.7-macosx-10.7-x86_64.egg
Extracting pysam-0.15.2-py3.7-macosx-10.7-x86_64.egg to /Users/drb/anaconda3/envs/hgvs_local/lib/python3.7/site-packages
Adding pysam 0.15.2 to easy-install.pth file
'''

**Comment by reece** [comment]
@Deena-B: It looks to me that you've solved this issue. Closing. 

Why are you using conda rather than the more common pip+setuptools? I'm not inclined to add alternative instructions when the standard route should be strongly preferred (pending a good reason that the standard route doesn't work).
