### ISSUE TITLE
Create an VariantMapper instance section of Quick Start

### ISSUE THREAD

**Issue by langitem** [biocommons/hgvs#547]
Right now the documentation shows:

`>>> import hgvs.variantmapper`

`>>> variantmapper = hgvs.assemblymapper.AssemblyMapper(hdp, assembly_name="GRCh37")`

but I am getting the error:
**AttributeError: module 'hgvs' has no attribute 'assemblymapper'**

I suggest using the import statement instead:
`>> import hgvs.assemblymapper`

I also suggest using the latest genome version:
`>>> variantmapper = hgvs.assemblymapper.AssemblyMapper(hdp, assembly_name="GRCh38")`

**Comment by reece** [comment]
@langitem This looks fixed in the current unreleased dev branch. Closing.

Please review https://hgvs.readthedocs.io/en/latest/quick_start.html and reopen if you think clarification is needed.
