### ISSUE TITLE
Sporadic errors during testing caused by sporadic NCBI rejections

### ISSUE THREAD

**Issue by reece** [biocommons/hgvs#553]
Tests fail periodically when NCBI rejects URLs after several similar requests in a short span. This causes testing to fail sporadically.  For example, https://travis-ci.org/biocommons/hgvs/jobs/516280914.

One or more of the following should be considered:
- biocommons/bioutils#16
- wrap seqfetcher in lru_cache
- Use PyVCR to create persistent cache for testing (and eliminate network requests entirely)

**Comment by reece** [comment]
biocommons/bioutils#16 was implemented. Testing hgvs using that package works. Immediate problem fixed. Closing now, but expect to pick up pyvcr work in other testing overhauls and after obsoleting 2.7 support.

**Comment by reece** [comment]
Accidentally closed through typo on commit message. :-(

**Comment by ecalifornica** [comment]
Does #697 satisfy this?

**Comment by reece** [comment]
This issue was closed by stalebot. It has been reopened to give more time for community review.  See [biocommons coding guidelines](https://biocommons.org/contributing/coding-guidelines/) for stale issue and pull request policies.  This resurrection is expected to be a one-time event.
