### ISSUE TITLE
Add hgvs_p formatting option for translation initiation variants

### ISSUE THREAD

**Issue by andreas-invitae** [biocommons/hgvs#557]
For variants that impact the translation initiation codon (e.g. `NM_007199.2:c.2T>C`) hgvs currently produces an hgvs_p string that is `p.?`. An alternative way to represent this would be `p.Met1?`. Would it be interesting to receive a PR that adds a formatting option for this?

**Comment by reece** [comment]
Sure! Both are legal representations and, as far as I can tell, the recommendations have no preference.
