### ISSUE TITLE
getting chromosome name

### ISSUE THREAD

**Issue by andrewcchang** [biocommons/hgvs#563]
Hi, 

Thank you for making such a wonderful tool!

One question, the output of `parse_hgvs_variant` contains Gene name. Is it easy to add **Chromosome name** into hgvs.sequencevariant.SequenceVariant Class?

It will be helpful to get the chromosome name along with the genomic locations, because it can then directly be used for downstream analysis.

**Comment by reece** [comment]
@andrewcchang: Glad you like it! I love comments like that!

Yes, it would be easy to add. However, emitting the chromosome name in an HGVS expression is not standard and would lead to expressions that are not parseable by unaware tools.

I would like us (the HGVS committee) to support chromosome names, but we don't yet do so *except* in the context of ISCN. See https://varnomen.hgvs.org/bg-material/consultation/svd-wg004/.

I'm going to close this until there's a spec we can work from.
