### ISSUE TITLE
Fail to parse long variant

### ISSUE THREAD

**Issue by dariober** [biocommons/hgvs#564]
Hi- There seems to be a bug in parsing a long HGVS string? 

This works:

```
import hgvs.parser
hgvsparser = hgvs.parser.Parser()

var= hgvsparser.parse_hgvs_variant('ENSP00000478700.1:p.Thr377delinsArgTrpArgIleThrSerHisSerTer')
```

An additional AA at the end throws an error: 

```
var= hgvsparser.parse_hgvs_variant('ENSP00000478700.1:p.Thr377delinsArgTrpArgIleThrSerHisSerTerSer')

/home/dario/.local/lib/python3.6/site-packages/hgvs/parser.py in rule_fxn(s)
    131                 except ometa.runtime.ParseError as exc:
    132                     raise HGVSParseError("{s}: char {exc.position}: {reason}".format(
--> 133                         s=s, exc=exc, reason=exc.formatReason()))
    134 
    135             rule_fxn.__doc__ = "parse string s using `%s' rule" % rule_name

HGVSParseError: ENSP00000478700.1:p.Thr377delinsArgTrpArgIleThrSerHisSerTerSer: char 57: expected EOF
```

I got this from a real HGVS string which in fact is even longer than this.

Version:

```
hgvs.__version__
'1.3.0.post0'

Python 3.6.7
```

**Comment by reece** [comment]
The hgvs grammar does not permit amino acids after Ter. If you replace the Ter with a real AA, it'll work fine.

The error `char 33: expected EOF` means that something came after the expected end of input. (EOF=end of file. That's a cryptic error message, but it's not easily changed.)

You'll get the same error with `ENSP00000478700.1:p.Thr377delinsTerArg`

The length of the insert is limited only by computer memory.
