### ISSUE TITLE
Deletion positions shifted after normalization of variant

### ISSUE THREAD

**Issue by NataliaSirera** [biocommons/hgvs#565]
Hi there!
After normalization of this variant, I obtained a very strange result: the deletion positions have been shifted with no explanation from 1822-1833 to 1828-1839
``
raw_c = 'NM_199242.2:c.1822_1833del'
``
``
var_c = hp.parse_hgvs_variant(raw_c)
``
``
var_c
``
SequenceVariant(ac=NM_199242.2, type=c, posedit=1822_1833del, gene=None)

``
hn.normalize(var_c)
``
SequenceVariant(ac=NM_199242.2, type=c, posedit=1828_1839del, gene=None)

**Comment by NataliaSirera** [comment]
It also happened with variant ``NM_006949.3:c.1252_1255del`` which shifted to ``NM_006949.3:c.1254_1257del`` and variant ``NM_006949.3:c.301_303del`` which shifted to ``NM_006949.3:c.303_305del``

**Comment by reece** [comment]
Working as expected. 

```python
>>> raw_c = 'NM_199242.2:c.1822_1833del'
>>> var_c = hp.parse_hgvs_variant(raw_c)
>>> str(var_c), str(hn.normalize(var_c))
('NM_199242.2:c.1822_1833del', 'NM_199242.2:c.1828_1839del')

# disable automatic normalization when projecting variant to other coordinates 
>>> am38.normalize = False

# c. are based at the translation start site
# n. coords are based at the start of the sequence, and so are easier to use when fetching sequence 
>>> var_n = am38.c_to_n(var_c)
>>> str(var_n), str(hn.normalize(var_n))
('NM_199242.2:n.2202_2213del', 'NM_199242.2:n.2208_2219del')

# fetch_seq uses interbase coordinates!
>>> hdp.seqfetcher.fetch_seq("NM_199242.2", 2200, 2240)
'GGTGCAGCGCGCTGTGCAGATGGATGAGCTGGTGCCCCTG'

```

```
|2201     |2211     |2231     |2231
1234567890123456789012345678901234567890
GGTGCAGCGCGCTGTGCAGATGGATGAGCTGGTGCCCCTG
 ^^^^^^^^^^^^
       ^^^^^^^^^^^^
 ^^^^^^      ^^^^^^
 prefix      suffix
```

Note that the prefix and suffix sequences are identical (GTGCAG). So, deleting n.2202_2213 and deleting n.2208_2219 result in exactly the same sequence. These coordinates correspond to the c. coordinates you observed.
