### ISSUE TITLE
synonymous mutation in start codon comes back with no posedit on var_p object

### ISSUE THREAD

**Issue by akeeeshi** [biocommons/hgvs#566]
Hello,

The variant below is an example of when the reference genome disagrees with the transcript reference. As seen the projection to c_dot leads to a posedit call of "2=" and the information from the NCBI seen [here](https://www.ncbi.nlm.nih.gov/nuccore/NM_052902.2) shows that the first amino acid is indeed the start codon. This is in contrast to how this protein would be constructed if using the genomic sequence (see image below)

<img width="1420" alt="Screen Shot 2019-09-03 at 3 46 03 PM" src="https://user-images.githubusercontent.com/19749361/64203865-6fd72b80-ce62-11e9-96c6-e05f232b2a72.png">

In this particular situation the variant in question comes back with a var_p posedit of None instead of (Met1=). Is there any particular reason this is the case? Is this expected behavior?

**Example Code:**

`In [13]: hgvs_g = 'NC_000002.11:g.220462640G>T'`
`In [14]: var_g = hp.parse_hgvs_variant(hgvs_g)`
`In [15]: hp = hgvs.parser.Parser()`
`In [16]: hdp = hgvs.dataproviders.uta.connect()`
`In [17]: am = hgvs.assemblymapper.AssemblyMapper(hdp, assembly_name='GRCh37', alt_aln_method='splign', replace_reference=True)`
`In [18]: transcripts = am.relevant_transcripts(var_g)`

`In [19]: transcripts`
`Out[19]: ['NM_052902.2', 'NM_052902.3']`

`In [20]: var_c = am.g_to_c(var_g, 'NM_052902.2')`

`In [21]: var_c`
`Out[21]: SequenceVariant(ac=NM_052902.2, type=c, posedit=2=)`

`In [22]: var_p = am.c_to_p(var_c)`

`In [23]: var_p`
`Out[23]: SequenceVariant(ac=NP_443134.2, type=p, posedit=None)`

Please let me know what you think. Happy to help dig in further if need be.

**Comment by reece** [comment]
I can't reproduce this. What version are you using?

It is very helpful to me if you use hgvs-shell to generate bug reports. Like this:

```
snafu$ hgvs-shell

hgvs-shell -- interactive hgvs
hgvs version: 1.3.1.dev0+g83cde96.d20190515
data provider url: postgresql://anonymous:anonymous@uta.biocommons.org/uta/uta_20180821
schema_version: 1.1
data_version: uta_20180821
sequences source: SeqRepo (/usr/local/share/seqrepo/latest)

...

In [1]: hgvs_g = 'NC_000002.11:g.220462640G>T'
In [2]: var_g = parser.parse_hgvs_variant(hgvs_g)
In [3]: var_c = am37.g_to_c(var_g, 'NM_052902.2')
In [4]: var_p = am37.c_to_p(var_c)
In [5]: var_p
Out[5]: SequenceVariant(ac=NP_443134.2, type=p, posedit=Met1?, gene=None)

```

I realize that it might be more work for you to put it in this format, but I hope that it pays off in response time!

**Comment by reece** [comment]
Also, if you use UCSC to visualize, it helps if you tell me whether you've also verified that UCSC's coordinates are correct (they use BLAT, which differs from NCBI's splign in some cases).

**Comment by akeeeshi** [comment]
I apologize for not including the version information. I'll be sure to check blat vs. splign alignment in the future as well. This is what I was using.

```
#########################################################################
hgvs-shell -- interactive hgvs
hgvs version: 1.2.4
data provider url: postgresql://anonymous:anonymous@uta.biocommons.org/uta/uta_20161216
schema_version: 1.1
data_version: uta_20161216
sequences source: local (SeqRepo)
```

I am able to reproduce the behavior (Met1?) you show above when using the newer version of hgvs (1.3.0.post0). 

Is there an explanation for the Met1? output vs. describing the variant as Met1=? Is it just the fact that affecting structure of the translation initiation region in any way could have an unpredictable outcome?

**Comment by reece** [comment]
Thanks for confirming that 1.3.0 works. I don't recall why that behavior would have changed between versions.

The `Met1?` is recommended as a special case because ATG at c.1-3 is a translation signal, not just an amino acid, so it's not clear that you'll get a protein at all.

Try googling for "HGVS met1?".
