### ISSUE TITLE
 HGVS package 1.3 del and dup sequence omitted

### ISSUE THREAD

**Issue by suesui117** [biocommons/hgvs#568]
Hello,
I have a question regarding the updated HGVS package for del and dup for variants
I'm transitioning from HGVS python package 0.4 version to 1.3 and I noticed the newest HGVS package is dropping all the sequences after del and dup. For example, NM_000414.3:c.842dupA will be reported at NM_000414.3:c.842dup. Is this correct? I also found the two threads regarding this new update:
https://github.com/biocommons/hgvs/issues/404
https://github.com/biocommons/hgvs/issues/424

if this is correct. I'd like to know where can I set the max_ref_length not to 0? Where can I modify this?

Thank you very much in advance for your help and time!

**Comment by reece** [comment]
Documentation for configuration is weak right now. (PR's welcome!)

For now, see these: 
* https://hgvs.readthedocs.io/en/stable/modules/config.html
* https://groups.google.com/forum/#!searchin/hgvs-discuss/config%7Csort:date/hgvs-discuss/kyyl8qwFidU/36g1Wby_EwAJ
