### ISSUE TITLE
Can hgvs left shift/align/shuffle variants?

### ISSUE THREAD

**Issue by xiaoqiwang19** [biocommons/hgvs#574]
Recently when I was using the HGVS package, I encountered a reverse transcript, NM_000546.5 is a reverse transcript. when I processed NM_000546.5:c.448_459del with hgvs, the result was NC_000017.10 :g.7578473_7578484del, the position is to the right of genome. In fact, this result is consistent with NC_000017.10 :g.7578471_7578482del. Is there a method for the hgvs package to get NC_000017.10 :g.7578471_7578483del from NM_000546.5 :c.448_459del ?  That is to say, can we get the genome coordinates on the left side of the genome when the transcript is a reverse transcript?  Could you give me some advice about dealing with this situation?
I really would like to get your help and look forward to your reply.

for example：
>>> var_c = hp.parse_hgvs_variant("NM_000546.5:c.448_459del")
>>> am.c_to_g(var_c)
SequenceVariant(ac=NC_000017.10, type=g, posedit=7578473_7578484del)

**Comment by reece** [comment]
@xiaoqiwang19 Yes, hgvs can be made to left shift variation. But, left-shifted variation is non-standard and should *never* be shared or published. Please be careful to not distribute such variation.

You can do this:
```
>>> var_c = hp.parse_hgvs_variant("NM_000546.5:c.448_459del")
>>> var_g = am37.c_to_g(var_c)
>>> str(var_g)
'NC_000017.10:g.7578473_7578484del'

>>> from hgvs.normalizer import Normalizer
>>> hn5 = Normalizer(hdp, shuffle_direction=5)
>>> str( hn5.normalize(var_g) )
'NC_000017.10:g.7578471_7578482del'

# 3' is the default, so this has no effect on the original g. variant
>>> hn3 = Normalizer(hdp, shuffle_direction=3)
>>> str( hn3.normalize(var_g) )
'NC_000017.10:g.7578473_7578484del'

```

Please close this issue if this answers your question.

**Comment by xiaoqiwang19** [comment]
Your answer has solved my question. Thank you very much.
