### ISSUE TITLE
how can I use hgvs locally and parallel?

### ISSUE THREAD

**Issue by wentgithub** [biocommons/hgvs#577]
thanks for this powerful package, I am trying to use it, and compare it with the pyhgvs. I am encouterted with some tough question.

I first do as the https://hgvs.readthedocs.io/en/stable/installation.html to install, and then do as https://github.com/biocommons/hgvs 
```
mkvirtualenv hgvs-test
(hgvs-test)$ pip install --upgrade setuptools
(hgvs-test)$ pip install hgvs
(hgvs-test)$ python
```
I install numpy also due to breakdown in installing hgvs, finally it go well.

1  when I try to do normalize, it seems that it needs to connect the internet, and stopped here for  a whole day, so how I can use it locally?

![image](https://user-images.githubusercontent.com/48668142/70303105-b5c4d680-1839-11ea-93a2-6ebc6b6a4665.png)

2 must I creat a virtualenv for each sample  and then do as the following
mkvirtualenv hgvs-test
(hgvs-test)$ pip install --upgrade setuptools
(hgvs-test)$ pip install hgvs

I think I must misunderstand that, so how can do parallel?

thanks a lot

**Comment by wentgithub** [comment]
when I tried to pull seqrepo, too slow
![image](https://user-images.githubusercontent.com/48668142/70326901-96956b80-1870-11ea-8937-1fc950d2656d.png)

**Comment by reece** [comment]
1. It sounds like you need to learn about parallelism in Python generally. Just google "Python parallel". The tutorials at realpython.com are particularly good.

1. You only need (and want) one virtualenv. The same venv will be used for all processes and threads.

1. Your connection seems to be very slow. There's nothing that I can do about that. 

Good luck!

**Comment by reece** [comment]
Please see https://hgvs.readthedocs.io/en/stable/getting_help.html for how to ask questions. Github issues are for issues with the code.
