### ISSUE TITLE
how to use locally 

### ISSUE THREAD

**Issue by wentgithub** [biocommons/hgvs#578]
thanks a lot.
I have two questions want to know
1: 
after installing UTA and SeqRepo 
and add the following two  env variable  to my ~/.bashrc
export HGVS_SEQREPO_DIR=/usr/local/share/seqrepo/20160906
 export UTA_DB_URL=postgresql://anonymous@localhost:15032/uta/uta_20170117.

and will all the command when I use hgvs functions, the package will use all local database  automaticlly?

or should I set db_url or something else?
hgvs.dataproviders.uta.connect(db_url=None, pooling=False, application_name=None, mode=None, cache=None)

2: must this packages know the small version of a transcript, for example 
NM_001166478.1:c.35_36insT, can the input be NM_001166478:c.35_36insT ?

3  can you give me a md5 value of seqrepo, due to it is so big, I want to check the file  when downloaded

**Comment by reece** [comment]
Please see https://hgvs.readthedocs.io/en/stable/getting_help.html for how to ask questions. Github issues are for issues with the code.
