### ISSUE TITLE
import.im6: unable to grab mouse 

### ISSUE THREAD

**Issue by wentgithub** [biocommons/hgvs#579]
when I do
` import hgvs.dataproviders.uta,`
 it gives the following error.

import.im6: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9047.

**Comment by reece** [comment]
hgvs and components have nothing to do with X windows. You'll need to look for other causes.

**Comment by wentgithub** [comment]
I have tried my best to solve this, still no method.

and I think the parallel is **too cumbersome to do**, beacause my each sample has its own directory , **I can not wait all the sample to complete its own annovar annotation and then do the hgvs process**, because each has its own different further analysis
