### ISSUE TITLE
psycopg2.OperationalError: could not connect to server: Connection refused

### ISSUE THREAD

**Issue by wentgithub** [biocommons/hgvs#580]
I google this error in #277 
but it seems that my error it is because of "Sorry... the password is also "anonymous" (no quotes)"

I set the env 
```
export UTA_DB_URL=postgresql://anonymous@localhost:15032/uta/uta_20170117
export HGVS_SEQREPO_DIR=/data/ngs/softs/b_hgvs/seqrepo/seqrepo/2019-06-20
```
and do as following
>>> import hgvs.dataproviders.uta
>>> hdp = hgvs.dataproviders.uta.connect()

![image](https://user-images.githubusercontent.com/48668142/70385447-5c3ee200-19c8-11ea-86de-9e9647d93d96.png)

I also tried the method in https://github.com/biocommons/uta/

`psql -h localhost -p 50827 -U anonymous -d uta -c 'select * from uta_20150827.meta'`
psql: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 50827?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting

is there anything I am wrong, I do not know how to solve.

**Comment by wentgithub** [comment]
about the docker command in your guide, I tried twice, it got error the same.
I just copy the command in your user-guide
![image](https://user-images.githubusercontent.com/48668142/70385739-fb64d900-19ca-11ea-814d-8afda2a20b94.png)

**Comment by reece** [comment]
Where did you get 50827? If you did what's shown above, it should be 15032.

**Comment by wentgithub** [comment]
> Where did you get 50827? If you did what's shown above, it should be 15032.

I do not know, I just do as the guide told me , first docker pull, then export the port the default setting

**Comment by wentgithub** [comment]
here is another again new try, still showing connect unreachable, but not the same
![image](https://user-images.githubusercontent.com/48668142/70402913-0291f280-1a70-11ea-8d85-64b71e7cecf7.png)

**Comment by wentgithub** [comment]
with the test on, the connect seems change all the time, sometimes ok, sometime unreachable
<br>
<br>

**Comment by 2236529177** [comment]
any updates on this?
![image](https://user-images.githubusercontent.com/25199946/71412269-f02ad200-2687-11ea-9cba-82fb1dbc078d.png)

**Comment by reece** [comment]
There are two distinct questions on this issue. 

1) Regarding the port issues, the short advice is to ensure that the port used when executing docker matches the port in the UTA_DB_URL. You should be able to connect to the UTA database the UTA_DB_URL, with the schema removed. For example, with:
```$ export UTA_DB_URL=postgresql://anonymous:anonymous@localhost:5432/uta/uta_20180821```
connect with
```$ psql postgresql://anonymous:anonymous@localhost:5432/uta```

2) Regarding the `dupT`, that's minor. The spec permits either. In the [1.0.0 release](https://hgvs.readthedocs.io/en/stable/changelog/1.0/1.0.0.html#new-features), we added the ability to control the max length of the reference sequence to display. 

By default, as you noted:
```
>>> v = hp.parse("NM_001166478.1:c.30_31insT")                                                                                                                                                                                   
>>> str(hn.normalize(v))                                                                                                                                                                                                         
'NM_001166478.1:c.35dup'
```

Set the maximum ref seq length to 5:
```
>>> import hgvs                                                                                                                                                                                                                  
>>> hgvs.global_config.formatting.max_ref_length = 5                                                                                                                                                                             
>>> str(hn.normalize(v))                                                                                                                                                                                                         
'NM_001166478.1:c.35dupT'
```

**Comment by reece** [comment]
This appears to have been resolved. Closing.
