### ISSUE TITLE
Support for fusion hgvs

### ISSUE THREAD

**Issue by xiucz** [biocommons/hgvs#599]
Hi, 
Thanks for your great work.
I have some fusion events, like 
```
1, Fusion: EML4_ENST00000318522.5:intron:6|-chr2:42493486___ALK_ENST00000389048.3:intron:19|+chr2:29447415
```
How can I use this tool to translate it into hgvs format, something like: `ENST00000367595.3(ACBD6):r.1_1261_ENST00000366932.3(RRP15):r.736_7771`

Thank you.
Xiucz

**Comment by reece** [comment]
The hgvs package doesn't currently support fusions and didn't exist in the HGVS recommendations at the time it was written.

I'm afraid that you'll have to implement fusion support yourself, possibly using the hgvs package to represent the two regions.

**Comment by xiucz** [comment]
@reece  
Thank you, if you know more, can you tell me how to get the `r.` from the `g.` and transcript info ?
Thank you.

**Comment by reece** [comment]
r. is essentially the same as n., but with an RNA alphabet. 

So, I think you should be able to use `g_to_n` and `n_to_g` methods, and then stitch the two together.

If you get this working, please share your experience on the mailing list!

**Comment by reece** [comment]
This issue was closed by stalebot. It has been reopened to give more time for community review.  See [biocommons coding guidelines](https://biocommons.org/contributing/coding-guidelines/) for stale issue and pull request policies.  This resurrection is expected to be a one-time event.
