### ISSUE TITLE
Investigate replacing psycopg2 with asyncpg

### ISSUE THREAD

**Issue by reece** [biocommons/hgvs#603]
[asyncpg](http://magic.io/blog/asyncpg-1m-rows-from-postgres-to-python/) is a pure-python python library with support for asyncio. In principle, this would obviate libpq (see #199).

**Comment by reece** [comment]
This issue was closed by stalebot. It has been reopened to give more time for community review.  See [biocommons coding guidelines](https://biocommons.org/contributing/coding-guidelines/) for stale issue and pull request policies.  This resurrection is expected to be a one-time event.

**Comment by jsstevenson** [comment]
For what it's worth, there's also a newer [Psycopg version](https://www.psycopg.org/psycopg3/) now.
