### ISSUE TITLE
hgvs_p shows Ter, although no new stop codon got introduced.

### ISSUE THREAD

**Issue by andreasprlic** [biocommons/hgvs#607]
Hi,

Looks like the following code results in a slightly incorrect hgvs_p string:

```
In [1]: hgvs_c = 'NM_002485.4:c.2256_2258del'
In [2]: var_c = parse(hgvs_c)
In [3]: c_to_p(var_c)
Out[3]: SequenceVariant(ac=NP_002476.2, type=p, posedit=(Arg754Ter), gene=None)
```

I would expect that the created variant is actually `Arg754del`, rather than `Ter`, since no new stop codon got introduced.

Here the environment for this variant:
<img width="294" alt="Screen Shot 2020-09-28 at 2 48 37 PM" src="https://user-images.githubusercontent.com/187599/94491394-075d9980-019d-11eb-8931-4e250e8b1b17.png">

Note: this is a reverse strand transcript, as such the protein sequence needs to get read from right->left, but the displayed genomic reference sequence is forward strand.

Another note: I believe this is Arg754del, rather than Arg752del or Arg753del, since the HGVS spec suggests that all (protein) reference sequences need to get described in the most C-terminal possible position.

**Comment by reece** [comment]
This issue was closed by stalebot. It has been reopened to give more time for community review.  See [biocommons coding guidelines](https://biocommons.org/contributing/coding-guidelines/) for stale issue and pull request policies.  This resurrection is expected to be a one-time event.
