### ISSUE TITLE
i am using docker compose file and to store some data i am using postgresql

### ISSUE THREAD

**Issue by deepik27** [biocommons/hgvs#610]
i am using flask post api with docker compose file and postgres database also...but just when i am using flask post api and docker compose its working fyn but when i use postgres i am getting this error  
and please help anyone    

![Screenshot from 2021-01-18 14-40-03](https://user-images.githubusercontent.com/64435256/104894732-13af7180-599b-11eb-92da-c7fb58ad5188.png)
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
api_1    | psycopg2.OperationalError: could not connect to server: Connection refused
api_1    |      Is the server running on host "127.0.0.1" and accepting
api_1    |      TCP/IP connections on port 5432?

**Comment by reece** [comment]
This issue was closed by stalebot. It has been reopened to give more time for community review.  See [biocommons coding guidelines](https://biocommons.org/contributing/coding-guidelines/) for stale issue and pull request policies.  This resurrection is expected to be a one-time event.
