### ISSUE TITLE
protein change annotation difference between hgvs and vep

### ISSUE THREAD

**Issue by kwuiee** [biocommons/hgvs#612]
When converting cdna change `NM_000348.4:c.653dup` to protein change, hgvs gives `NP_000339.2:Ser220LeufsTer14`, while vep gives `p.Ser219LeufsTer14` which seems to be right.
![图片](https://user-images.githubusercontent.com/23001268/117523728-81d08080-afec-11eb-8e0c-412d9686ecf1.png)

**Comment by andreasprlic** [comment]
Not sure what alignment you are using here? When I look this up in my genome browser, the alignment looks differently. There is a (indel) disagreement between the transcript and the reference genome somewhere upstream of this position, which I suspect might be causing this confusion. Does your alignment ^^^ incorporate that? 

<img width="1011" alt="Screen Shot 2021-05-10 at 9 52 04 AM" src="https://user-images.githubusercontent.com/187599/117696004-b0c62e00-b175-11eb-9164-d946a07e59be.png">

**Comment by kwuiee** [comment]
Thanks for answering my question. I'm using [IGV](https://github.com/igvteam/igv) for visualization. And you are right, there is a disagreement between the transcript and the reference genome.

When I look through the upstream, I found this
![图片](https://user-images.githubusercontent.com/23001268/117791897-60d28e80-b27d-11eb-96d7-12878fdf4151.png)
while in NM_000348.4 (note: reverse strand), it is three Gs.
![图片](https://user-images.githubusercontent.com/23001268/117792784-346b4200-b27e-11eb-88d1-5118fce75c20.png)
This is where problem comes from.

And when encounters with this kind difference, vep and igv ignore the problem codon, while hgvs uses genome sequence to deduce animo acid sequence, I guess.

**Comment by reece** [comment]
FWIW, failure to account for indels in coding regions is the #1 reason that hgvs differs from other software. Our 2018 update paper provides lots of examples for issues like this. https://pubmed.ncbi.nlm.nih.gov/30129167/

Because Ensembl transcripts are defined on the genome, it mostly doesn't have a notion of transcript sequences that differ from genomic sequence. In contrast, RefSeq transcript sequences are distinct from genomic sequences and are related through alignment, which may contain indels.

**Comment by reece** [comment]
This issue was closed by stalebot. It has been reopened to give more time for community review.  See [biocommons coding guidelines](https://biocommons.org/contributing/coding-guidelines/) for stale issue and pull request policies.  This resurrection is expected to be a one-time event.

**Comment by davmlaw** [comment]
Hi - HGVS correctly handles alignment gaps here. The bug is with Ensembl VEP - I have already [raised this issue with them](https://github.com/Ensembl/ensembl-vep/issues/1053)
