### ISSUE TITLE
AssemblyMapper has wrong import path on documentation examples

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [biocommons/hgvs#614]
Various examples of the documentation have 

`hgvs.variantmapper.AssemblyMapper`

but it should be

`hgvs.assemblymapper.AssemblyMapper`

I guess it was moved and the documentation wasn't updated. If I wanted to fix this, should I fork and make a pull request? If there is other procedure tell me.

**Comment by reece** [comment]
Hi @AgustinRamiroDiaz : Good catch. Yes, this is an unfortunate case of documentation lagging behind code after a rename. (I *thought* I searched for all occurrences...) 

Since this is easy, I'll take this one. But, yes, fork and PR would be great for future submissions.
