### ISSUE TITLE
normalize a whole hgvs

### ISSUE THREAD

**Issue by worker000000** [biocommons/hgvs#618]
Dear professor,
this package is really very useful, it really rescue mnay ngs data needed to be hgvs, a really big step in variant , thanks a lot.

#
I found many example in variants normalize, just use NM and cdna, but a whole hgvs contains a lot parts.
MSH6:NM_000179.2:exon5:c.3254delC:p.F1088Sfs*2
#
v = hp.parse_hgvs_variant("NM_000179.2:c.3254delC")
str(hn.normalize(v))
#  
I tried to do 
v = hp.parse_hgvs_variant("MSH6:NM_000179.2:exon5:c.3254delC:p.F1088Sfs*2")
str(hn.normalize(v))
but failed, is there a easy way to normalize ；also tools like annovar , they not supply NP number
g m c n r p
#
by the way, 
1 the nimor version of NM is a must, am I right, I tested it
2 is it ok to use the command in docker with local UTA?
![image](https://user-images.githubusercontent.com/25199946/122792260-9642b100-d2ec-11eb-9a7e-ad1654cb9b95.png)

**Comment by reece** [comment]
@worker000000 : Sorry for the long delay.

`MSH6:NM_000179.2:exon5:c.3254delC:p.F1088Sfs*2` is not a valid HGVS expression. HGVS is governed by the HGVS (aka VarNomen) recommendations at http://varnomen.hgvs.org/. I believe that this will parse if you remove the gene name and :exon5 string (I didn't test that).

Yes, the minor version should be included. The parser doesn't require this because it would require specific handling for NMs.

Does this answer your question?

**Comment by worker000000** [comment]
@reece thanks a lot for the helpful answer.
here still lacks p, how can i add that
![image](https://user-images.githubusercontent.com/25199946/135737028-d62d186b-f6e8-46e6-9b93-18f5e639a975.png)
![image](https://user-images.githubusercontent.com/25199946/135737034-9a5dfcb2-6d7b-44ae-8780-3ad10da0a24a.png)

**Comment by worker000000** [comment]
hgvs is 3 rule, and database like clinvar is left normalized,
will this lead to the miss of important clinical significanse

**Comment by worker000000** [comment]
![1633257163(1)](https://user-images.githubusercontent.com/25199946/135749859-3e7694ec-ab16-41af-9906-c8158b011986.png)
I saw this in issuses, but I install it through 
pip3 install hgvs
still met this

**Comment by worker000000** [comment]
<>
I installed it onced, but stopped because of internet, then once again, met this, how should I fix it. thanks a lot
<>

![image](https://user-images.githubusercontent.com/25199946/135751557-9301519d-ea22-4068-b3fb-ae7ed392568f.png)
