### ISSUE TITLE
normalization/projection edge cases near exon/intron boundaries 

### ISSUE THREAD

**Issue by paul-williams-tfs** [biocommons/hgvs#622]
Not sure if this is a bug or a request for help. I'm just starting to use this resource and it's been great so far. 

I have developed some code to convert VCF-style genomic variant representation to HGVS g. syntax then project to c. and ultimately p. notations. One thing I'm trying to assess is whether the generated c. / p. syntax is stable across different vcf representations (i.e., padded vs. parsimonious ref/alt alleles, indel alignment differences).

One particularly tricky variant is COSM26720, which involves a duplication of 12 nucleotides of genomic sequence. When right-aligned this insertion takes place within the exon, but it left-aligns into the intron. Hopefully the ASCII art makes things clear. EGFR is on the forward strand.

```
GRCh37
chr7:55248                   9
         9                   0
         8         9         0
         012345678901234567890123456789
         CTCCAGGAAGCCTACGTGATGGCCAGCGTG Wild-type
               GluAlaTyrValMetAlaSerVal
               762763764765766767768769

chr7:55248                               9
         9                               0
         8                     9         0
         0            12345678901234567890123456789
         CTCCAGGAAGCCTTCCAGGAAGCCTACGTGATGGCCAGCGTG NC_000007.13:g.55248980_55248981insTCCAGGAAGCCT
                           GluAlaTyrValMetAlaSerVal NM_005228.5:c.2284-5_2290dup
                           762763764765766767768769 NP_005219.2:p.?

chr7:55248                               9
         9                               0
         8         9                     0
         012345678901            234567890123456789
         CTCCAGGAAGCCTTCCAGGAAGCCTACGTGATGGCCAGCGTG NC_000007.13:g.55248992_55248993insTCCAGGAAGCCT
               GluAlaPheGlnGluAlaTyrValMetAlaSerVal NM_005228.5:c.2290_2291insTCCAGGAAGCCT
               762763            764765766767768769 NP_005219.2:p.Ala763_Tyr764insPheGlnGluAla                                 


```

If I follow the following steps, 
```
In :var_g_right = parse("NC_000007.13:g.55248992_55248993insTCCAGGAAGCCT")
In :var_g_left = parse("NC_000007.13:g.55248980_55248981insTCCAGGAAGCCT")
In :norm_g_right = normalize(var_g_right)
In :norm_g_left = normalize(var_g_left)
```

I find that norm_g_left is equal to norm_g_right is equal to NC_000007.13:g.55248981_55248992dup

When I try to map to the transcript sequence, I get some confusing results.

Mapping the un-normalized left-aligned representation complains that normalizing intronic variants is not supported (as expected):
```
In :var_c_left = g_to_c(var_g_left, "NM_005228.5")
WARNING:hgvs.assemblymapper:Normalization of intronic variants is not supported; returning unnormalized variant
```

Mapping the un-normalized right-aligned representation is not a problem, and I can then map to the protein, and it generates the protein change I would expect to see:
```
In :var_c_right = g_to_c(var_g_right, "NM_005228.5")
In :print(c_to_p(var_c_right))
NP_005219.2:p.(Ala763_Tyr764insPheGlnGluAla)
```

But when I map the normalized representation, I get the intronic variant normalization warning again, which is confusing, because it does not generate the protein change I would expect to see.

```
In : norm_c = g_to_c(norm_g_right, "NM_005228.5")
WARNING:hgvs.assemblymapper:Normalization of intronic variants is not supported; returning unnormalized variant
```

It's also a little complicated when there are indels on the reverse strand. Normalizing the genomic sequence can shift things to the right, which can lead to a similar situation. Am I doing something wrong here or is there something else I should be doing?

Thanks. My hgvs-shell output is below

############################################################################
hgvs-shell -- interactive hgvs
hgvs version: 1.5.1
data provider url: postgresql://anonymous@localhost:15032/uta/uta_20190928
schema_version: 1.1
data_version: uta_20190928
sequences source: SeqRepo (/usr/local/share/seqrepo/latest)

**Comment by reece** [comment]
This issue was closed by stalebot. It has been reopened to give more time for community review.  See [biocommons coding guidelines](https://biocommons.org/contributing/coding-guidelines/) for stale issue and pull request policies.  This resurrection is expected to be a one-time event.
