### ISSUE TITLE
Depend on psycopg2 rather than psycopg2-binary

### ISSUE THREAD

**Issue by DavidCain** [biocommons/hgvs#623]
Are you open to depending on `psycopg2` instead of `psycopg2-binary`, at least until alternate approaches remove the need for either package?

This may prove inconvenient, since `psycopg2-binary` is "is meant for beginners to start playing with Python and PostgreSQL without the need to meet the build requirements."

However, it's likely preferable to depend on `psycopg2` for production software.

Issues in flight which I believe would make this request irrelevant:
-------

- [make data provider dependencies optional][hgvs-optional-deps]
- [replace psycopg2 with asyncpg][hgvs-asyncpg]
- [use a REST interface, eliminating libpq dependency][hgvs-rest]

---------------

Why move away from `psycopg2-binary`?
=====================================
The psycopg2 project makes two recommendations in the [psycopg2 vs psycopg2-binary][psycopg2-vs-psycopg2-binary] docs:

> If you are the maintainer of a published package depending on `psycopg2` you shouldn’t use `psycopg2-binary` as a module dependency.

Secondarily:

> **For production use you are advised to use the source distribution.**

This means that any production software depending on `hgvs` will have to install `psycopg2-binary`.

History of the two packages
===========================
Starting with Psycopg2 2.8, there are now two packages (explained in the [2.7.4 release notes][psycopg2-274]):

- `psycopg2`: source distribution, advised for production.
- `psycopg2-binary`: "quickest way to install" (a "pre-compiled binary version")

There is substantial discussion in [an issue on the `psycopg2` project][gh-thread], which I won't re-summarize here, but one takeaway is that many Python packages now depend on `psycopg2-binary`, and others on `psycopg2`.

Ideally, all libraries just depend on `psycopg2`.

Alternate solutions to the split exist (like [`Provides-Dist` from PEP 345][provides-dist]).
However, the [`Provides-Dist` field is "rarely used"][provides-dist-rarely-used] and thus ignored most of the time.

[`hgvs` switched to `psycopg2-binary`][hgvs-switch-to-binary] shortly after the 2.7.4 release.

[psycopg2-274]: https://www.psycopg.org/articles/2018/02/08/psycopg-274-released/
[hgvs-asyncpg]: https://github.com/biocommons/hgvs/issues/603
[hgvs-optional-deps]: https://github.com/biocommons/hgvs/issues/199
[hgvs-asyncpg]: https://github.com/biocommons/hgvs/issues/603
[psycopg2-vs-psycopg2-binary]: https://www.psycopg.org/docs/install.html#psycopg-vs-psycopg-binary
[gh-thread]: https://github.com/psycopg/psycopg2/issues/674
[hgvs-switch-to-binary]: https://github.com/biocommons/hgvs/commit/4c75a4e5
[provides-dist-rarely-used]: https://packaging.python.org/specifications/core-metadata/#provides-dist-multiple-use
[hgvs-rest]: https://github.com/biocommons/hgvs/issues/199#issuecomment-285513007
[provides-dist]: https://www.python.org/dev/peps/pep-0345/#provides-dist-multiple-use

**Comment by reece** [comment]
Thanks for taking the time to write up a clear request and background info.

hgvs originally to depended on psycopg2. Then, psycopg2 specifically recommended using the -binary for package dependencies and we switched. It appears that that recommendation has changed (or, perhaps I misunderstood the scope of their recommendation). I suspect that we could revert (i.e., you could submit a PR for) switching to psycopg2 immediately with no impact.

My preference is to jump to a REST interface and sidestep all of these issues. If performance warrants it, we can then add optional deps to provide a pure Python interface too.

Please consider [joining biocommons.slack.com](https://join.slack.com/t/biocommons/signup) to discuss further.

**Comment by DavidCain** [comment]
Thanks for the speedy response!

Yup, my hope is that the upcoming REST interface obviates the distinction between `psycopg2` and `psycopg2-binary`, but this switch should help in the interim.

In general, having dependencies be specified as optional extras is really, really helpful for folks who want to include `hgvs` in a production system, yet not pull in unwanted dependencies (e.g. https://github.com/biocommons/hgvs/issues/624)

Thanks again, will have a PR up soon.
