### ISSUE TITLE
Error: AttributeError: 'UTA_postgresql' object has no attribute '_pool'

### ISSUE THREAD

**Issue by hotsoupisgood** [biocommons/hgvs#652]
Hi,
I am getting an error when running using the postgres data provider:
`AttributeError: 'UTA_postgresql' object has no attribute '_pool'`
I am still looking into the issue but I can't seem to find the _pool getting initialized anywhere in the code.

**Comment by hotsoupisgood** [comment]
Turns out I am using a fork of this. Sorry!

**Comment by reece** [comment]
Please include enough information for us to reproduce the problem, like hgvs version and sample code.

On a quick scan of the code, I do think it's possible that the _pool attribute is unset in some circumstances, so I don't doubt the possibility of a bug

**Comment by davmlaw** [comment]
I can recreate this via:

```HGVS_CACHE_MODE=run pytest tests/test_hgvs_dataproviders_uta.py```

output:

```
Exception ignored in: <function UTA_postgresql.__del__ at 0x7f87adae0280>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hgvs/dataproviders/uta.py", line 515, in __del__
  File "/usr/local/lib/python3.10/dist-packages/hgvs/dataproviders/uta.py", line 519, in close
AttributeError: 'UTA_postgresql' object has no attribute '_pool'
```

It does NOT occur when I run:

```
HGVS_CACHE_MODE=learn pytest tests/test_hgvs_dataproviders_uta.py
```

So I suspect it's due to cache...
