### ISSUE TITLE
Improve Parser startup time by storing generated Python code

### ISSUE THREAD

**Issue by davmlaw** [biocommons/hgvs#661]
Instantiating the Parser() class can take ~1.5s, it calls Parsley to generate a Python class, writes it to disk and then loads it as a module.

An alternative would be to generate the Python file once as part of the build process, then check it in (it's only 3044 lines long) then used it as normal code. This reduces the startup time from 1.5s to <2ms

It has been noted in #585 that this slows down unit testing. I made the change and ```time make test``` went from:

```
# Original code
real    3m59.550s
user    1m43.374s
sys    0m0.448s
```

to:

```
real    2m35.806s
user    0m17.217s
sys    0m0.309s
```

A lot of this is network time to UTA, so it's an 80% reduction in test user time from 103s -> 17.2s

**Creating the Python file**

```
import os
from ometa.grammar import OMeta
from ometa.builder import writePython


grammar_file = "src/hgvs/_data/hgvs.pymeta"
generated_code_dir = "src/hgvs/generated"

g = OMeta(open(grammar_file).read(), name="Grammar")
tree = g.parseGrammar("Grammar")
source = writePython(tree, "Grammar")

# Create a package for the new file (I assume we want Python2 compatability)
if not os.path.exists(generated_code_dir):
    os.mkdir(generated_code_dir)
    package_filename = os.path.join(generated_code_dir, "__init__.py")
    with open(package_filename, "w") as _:
        pass
    

source_filename = os.path.join(generated_code_dir, "hgvs_grammar.py")
with open(source_filename, "w") as source_file:
    source_file.write(source)
```

**Loading from Parser class:**

```

# import new code
from hgvs.generated.hgvs_grammar import createParserClass

class Parser(object):
    def __init__(self, grammar_fn=None, expose_all_rules=False):
        bindings = {"hgvs": hgvs, "bioutils": bioutils, "copy": copy}
        if grammar_fn is None:
            self._grammar = parsley.wrapGrammar(createParserClass(ometa.runtime.OMetaGrammarBase, bindings))
        else:
            # Still allow other grammars if you want
            with open(grammar_fn, "r") as grammar_file:
                self._grammar = parsley.makeGrammar(grammar_file.read(), bindings)
        self._logger = logging.getLogger(__name__)
        self._expose_rule_functions(expose_all_rules)
```

**Comment by davmlaw** [comment]
Happy to make a pull request if you like the idea.

Please let me know where the generation script should go ("sbin"?) and whether generation should be in the Makefile or we just remember to run it when the "hgvs.pymeta" changes and I can add a comment there explaining what to do

**Comment by mbiokyle29** [comment]
This would be super nice to have. I have some code for pipeline that runs concurrently at it passes a single parser instance around since it takes so long to create.
