### ISSUE TITLE
Does this library have support for "?" as HGVS does?

### ISSUE THREAD

**Issue by wlymanambry** [biocommons/hgvs#682]
HGVS follows this convention: 
“?” (question mark) is used to indicate unknown positions (nucleotide or amino acid); g.(?_234567)_(345678_?)del

Is this supported by the library at all? An example variant would be: 
NM_002290.3 c.946-?_1336+?DUP

Thanks!

**Comment by davmlaw** [comment]
No, it doesn't yet. The issues have been raised here:

#331 - hgvs doesn't support uncertain offsets
#225 - support uncertain ranges 

We plan on trying to integrate our cyto labs data at work with molecular/sequencing so I hope to tackle this in the next 6-12 months. Keep an eye on the linked issues
