### ISSUE TITLE
Normalizer constructor doesn't pass the `validate` param to the VariantMapper constructor

### ISSUE THREAD

**Issue by mihaitodor** [biocommons/hgvs#704]
When initialising an `AssemblyMapper`, a new `Normalizer` is initialised [here](https://github.com/biocommons/hgvs/blob/c69e03fa8b84a00c360e72f05de0e83177598cac/src/hgvs/assemblymapper.py#L91-L93). However, the `Normaliser` initialisation instantiates a new `VariantMapper` [here](https://github.com/biocommons/hgvs/blob/c69e03fa8b84a00c360e72f05de0e83177598cac/src/hgvs/normalizer.py#L58), but it doesn't set the `prevalidation_level` field for this `VariantMapper`, which means that it will fall back to reading the global config [here](https://github.com/biocommons/hgvs/blob/c69e03fa8b84a00c360e72f05de0e83177598cac/src/hgvs/variantmapper.py#L74).

I'm looking to avoid making calls to seqfetcher for transcripts and I bumped into this issue.

**Comment by davmlaw** [comment]
Fixed w/Pull request
