### ISSUE TITLE
Investigate and improve hgvs performance

### ISSUE THREAD

**Issue by reece** [biocommons/hgvs#721]
| Difficulty | Expected Duration | Possible Mentors |
|-|-|-|
| Medium | 175h | @reece |

### Summary

The goal of this project is to collect profiling data for the hgvs package, identify and triage opportunities for improvement, and to undertake some of those improvements.

### Community Outcomes

Improving the performance of hgvs will create a better experience for users and may enable new uses, such as on-the-fly variant translation in user interfaces.

### Expected Results / Deliverables

- Collect and present performance profiling data for common operations in hgvs
- Discuss opportunities for improvement with the community in order to prioritize performance improvements
- Implement several performance improvements and collect data to demonstrate the value

### Required and Desired Skills

- Deep python experience, including performance profiling
- Ability to visualize code paths and identify areas of improvement

### Benefits to Intern

The intern will gain familiarity with the processing of sequence variants and refine his/her experience with performance improvements in code.

### How to apply

Students applying to this project should briefly describe their vision for this project, highlight their existing skills and the skills they would need to learn, and estimate an implementation timeline.

**Comment by yakshithkd23** [comment]
how to apply project ??
