### ISSUE TITLE
Is it possible to get hgvs official name  from "15-49716528-A-G"？

### ISSUE THREAD

**Issue by shizipo** [biocommons/hgvs#743]
like "https://rest.variantvalidator.org/VariantValidator/variantvalidator/hg19/15-49716528-A-G/mane_select/" ?

get "NC_000015.9(NM_001330293.1):c.911-1617T>C"

**Comment by jsstevenson** [comment]
Hey @shizipo!

I don't think this is possible with out-of-the-box with HGVS. However, the [VRS-Python library](https://github.com/ga4gh/vrs-python) (which is biocommons-adjacent) does include a `translator` module that can ingest gnomAD-style variation descriptions and output them as HGVS strings (making use of the HGVS library under the hood). See https://github.com/ga4gh/vrs-python/blob/main/notebooks/getting_started/4_Exploring_the_AlleleTranslator.ipynb for more.

code snippet from @korikuzma 

```python
from biocommons.seqrepo import SeqRepo
from ga4gh.vrs.extras.translator import AlleleTranslator
from ga4gh.vrs.dataproxy import SeqRepoDataProxy

sr = SeqRepo(root_dir="/usr/local/share/seqrepo/latest")
seqrepo_dataproxy = SeqRepoDataProxy(sr)
allele_translator = AlleleTranslator(data_proxy=seqrepo_dataproxy)

gnomad_vcf = "15-49716528-A-G"
vo = allele_translator.translate_from(gnomad_vcf)
print(allele_translator.translate_to(vo, "hgvs"))
# ['NC_000015.10:g.49716528A>G']
```
